### PR TITLE
add libstanmath_mpi to makefile

### PR DESCRIPTION
**Pull request by wds15**
#### Submisison Checklist

- [ ] Run tests: `./runCmdStanTests.py src/test`
- [X] Declare copyright holder and open-source license: see below

#### Summary:
Sync makefile for MPI builds.

#### Intended Effect:
Bring makefiles in sync with stan-math in case of MPI enabled builds. This (should) fixes the currently broken tests on Jenkins which blocks all down-stream tests.

#### How to Verify:
Enable MPI (put `STAN_MPI= true` & `CC=mpicxx` in `make/local`) and then a 
`make build-mpi`
should work again.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Sebastian Weber

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by wds15** [comment]
Please see for more details

- here: https://github.com/stan-dev/math/pull/910
- and here: https://github.com/stan-dev/stan/pull/2558

**Comment by wds15** [comment]
We will probably still see failures in cmdstan since it is using a stan submodule which points to a stan-math which does not yet include the fixes to make/libstanmath_mpi. However, that updating chain does not work right now due to failing tests in cmdstan such that we are blocked. I think we need to manually update the submodules in stan and cmdstan to get into a working state again.

**Comment by wds15** [comment]
stan now is up to date, but cmdstan still needs a manual submodule update of stan, I think.

**Comment by seantalts** [comment]
Looks like it updated automatically?

**Pull request merged**
