### PR TITLE
Bugfix/763 765 makefiles

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

change make rules so that all necessary dependencies files are generated during model compilation for all models.

bug introduced in 2.20 - added a rule to `make/tests` which did the wrong thing w/r/t dependencies files - it correctly generated dependencies files for the cmdstan test models; but for all other models - compiled by the rules in `make/program` - the rule no longer created `.d` as part of the model compilation step.   

this resulted in bugs reported in https://github.com/stan-dev/cmdstan/issues/763 and https://github.com/stan-dev/cmdstan/issues/765.

#### Intended Effect:

trigger recompilation as needed whenever there's a change to a model of core stan.

#### How to Verify:

use make to build and rebuild programs - need to automate this test

to check that models are recompiled whenever the .hpp file goes away,  given a model `foo.stan`, do:
   + `make foo`
   +  `rm foo.hpp`
   + `make foo` - should trigger rebuild

- to check that models are recompiled whenever core Stan changes, given a model `foo.stan` do:
  + `make foo`
  + edit your favorite file in core Stan, e.g. stan/src/mcmc/var_adaptation.hpp
  + `make foo` - should trigger rebuild of main.o

#### Side Effects:

N/A

#### Documentation:

N/A

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
@rok-cesnovar - please review very carefully - not at all sure this is correct.  also, please suggest how to automate tests.

**Comment by mitzimorris** [comment]
@rok-cesnovar - why is this PR showing updates to stan-math - is this OK or a sloppy commit on my part?

**Comment by mitzimorris** [comment]
> The changes look good to me, other than the submodule changes. Those are a result of a bad commit (864df37).

@rok - what is the proper git incantation?

**Comment by rok-cesnovar** [comment]
In this case I would just revert the commit and redo the non-submodule changes and then be careful to only commit the modified file.

**Comment by mitzimorris** [comment]
jenkins, retest this please

**Comment by mitzimorris** [comment]
@rok-cesnovar -
> In this case I would just revert the commit and redo the non-submodule changes and then be careful to only commit the modified file.

tried this - git not happy - please help!

**Comment by rok-cesnovar** [comment]
There are now some test failures here:

```
[==========] Running 0 tests from 0 test cases.

[==========] 0 tests from 0 test cases ran. (0 ms total)

[  PASSED  ] 0 tests.

Running main() from stan/lib/stan_math/lib/gtest_1.8.1/src/gtest_main.cc

[==========] Running 4 tests from 1 test case.

[----------] Global test environment set-up.

[----------] 4 tests from CmdStan

[ RUN      ] CmdStan.optimize_default

sh: src/test/test-models/optimization_output: No such file or directory

src/test/interface/optimization_output_test.cpp:49: Failure

Expected equality of these values:

  0

  out.err_code

    Which is: 127

[  FAILED  ] CmdStan.optimize_default (3 ms)

[ RUN      ] CmdStan.optimize_bfgs

sh: src/test/test-models/optimization_output: No such file or directory

src/test/interface/optimization_output_test.cpp:64: Failure

Expected equality of these values:

  0

  out.err_code

    Which is: 127

[  FAILED  ] CmdStan.optimize_bfgs (3 ms)

[ RUN      ] CmdStan.optimize_lbfgs

sh: src/test/test-models/optimization_output: No such file or directory

src/test/interface/optimization_output_test.cpp:79: Failure

Expected equality of these values:

  0

  out.err_code

    Which is: 127

[  FAILED  ] CmdStan.optimize_lbfgs (2 ms)

[ RUN      ] CmdStan.optimize_newton

sh: src/test/test-models/optimization_output: No such file or directory

src/test/interface/optimization_output_test.cpp:94: Failure

Expected equality of these values:

  0

  out.err_code

    Which is: 127

[  FAILED  ] CmdStan.optimize_newton (2 ms)

[----------] 4 tests from CmdStan (10 ms total)



[----------] Global test environment tear-down

[==========] 4 tests from 1 test case ran. (10 ms total)

[  PASSED  ] 0 tests.

[  FAILED  ] 4 tests, listed below:

[  FAILED  ] CmdStan.optimize_default

[  FAILED  ] CmdStan.optimize_bfgs

[  FAILED  ] CmdStan.optimize_lbfgs

[  FAILED  ] CmdStan.optimize_newton

```

I think some files are not generated.

**Comment by mitzimorris** [comment]
the fix to the makefiles assumes that  all stan programs in test/models
will compile.  is this a valid assumption?

**Comment by rok-cesnovar** [comment]
I would say so. 

I mean, bottom line, tests passed. If any of them should not that is a separate issue for me.

**Pull request merged**
