### PR TITLE
Fixes problems with Windows tests

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

The CmdStan tests were failing in Windows because additional test executables weren't being built properly.

This PR adjusts the make targets so the intermediate executables are built.

(I've verified that this still works on Mac.)

#### Intended Effect:

Fixes Windows builds.

#### How to Verify:

From a clean CmdStan repo in Windows, type:
```
.\runCmdStanTests.py -j4 src/test/interface
```

#### Side Effects:

None.

#### Documentation:

None.

#### Reviewer Suggestions: 

@seantalts 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Generable

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Thanks.

I think (but can't be sure) that the modifications made to the makefiles
somehow skips the .o files as intermediate targets. Whatever caused it,
this works.

**Comment by seantalts** [comment]
I checked out a092b1928115480daf696c2cbfddb6fc41116b51 from July 28 and v2.15.0 and they both seemed to have the problem...  I'm trying to find a commit when they work. I'm just running `make clean-all; python runCmdStanTests.py -j4 src/test/interface` but all with RTools 3.3. Maybe this changed with the newer gcc?

**Comment by seantalts** [comment]
Checked v2.14.0 and also seems broken. But I can confirm this branch works on my windows desktop at home though!

**Comment by syclik** [comment]
At least it works now! It could have been a problem we just didn't know
about for a while. Thanks!

**Pull request merged**
