### PR TITLE
update pedantic_mode branch Jenkins build 60->62

### PR DESCRIPTION
**Pull request by rybern**
I made a small fix to the pedantic mode branch (bizarre Fmt bug!) and ran a new Jenkins build, 62. Now trying to update the CmdStan branch.

Are PRs like this the best way to push changes to the CmdStan test branch?

@rok-cesnovar

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Sure, though a PR to a custom branch like this is a bit overkill for me :).

Do you have permissions on the stan-dev/cmdstan repo to just push directly to the branch? That is work directly on this repo not a fork? I think you should have them. That is much simpler I guess.

**Comment by rybern** [comment]
I don't appear to have them, pushing directly to this branch gave me a permissions error.

Also, looks like I messed this up somehow, it isn't finding the '--warn-pedantic' flag so I guess I built the wrong version..

**Comment by rok-cesnovar** [comment]
No no, the tests on cmdstan always use the nightly build of stanc3. Ignore those.

**Comment by rok-cesnovar** [comment]
@mitzimorris can you give Ryan the rights to push to the stan-dev/cmdstan repo? I am not sure I am authorized to do that.

**Comment by rybern** [comment]
I'm getting the same error (no --warn-pedantic flag) attempting to run through CmdStanR - I'll figure it out :)

**Comment by rok-cesnovar** [comment]
Ah, I see what happened. The stanc3-test-binaries job got restarted for some unknown reason.
And a job looses its parameters on a restart. @serban-nicusor-toptal those happened to me a few times also.

@rybern just start the binaries again and ping me here to update the number.

**Comment by serban-nicusor-toptal** [comment]
`got restarted for some unknown reason` - I've noticed this lately, reason why the job fails is that the machine does down. We never had this issue so I'm not entirely sure why now, nothing seems to have changed. A day ago the old imac machine was rebooting during some builds, to fix that I've reduced parallel from 6 to 4 which seems to fix it, which points to a load issue for that machine.
Please if you ran into this kind of error let me know so I'll look into it and fix it. Thanks

**Comment by rybern** [comment]
@rok-cesnovar Build successful, ready to update to 63

**Comment by rok-cesnovar** [comment]
Done.

**Comment by rybern** [comment]
@mitzimorris Would it be possible for me to get write permission to CmdStan? It would make it easier if I could push to this Pedantic Mode test branch instead of bothering Rok.

**Comment by rok-cesnovar** [comment]
@rybern Updated the branch to 82. Really not a problem if you tag me to update until the permissions are sorted out. Takes 10 seconds.

**Comment by rybern** [comment]
@rok-cesnovar Hey Rok, could you update to 85? Thanks!

**Comment by rok-cesnovar** [comment]
Done. 

I do have to warn you that the latest github version of cmdstanr no longer has the repo_clone in install_cmdstan. We decided to remove it. 

You can achieve the same using:

```R
repo_url <- "https://github.com/stan-dev/cmdstan"
repo_branch <- "pedantic_mode"
install_dir <- # set install dir here
git_args <- c("clone", "--recursive",  repo_url, paste0("-b", repo_branch), install_dir)
processx::run(
  command = "git",
  args = git_args
)
```

**Comment by rybern** [comment]
Gotcha. Thanks!

**Pull request merged**
