### PR TITLE
Feature/659 diagnose verbose

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
Added output stmts for:
 - names of csv files parsed
 - msgs for each diagnostic;  if diagnostic is OK, outputs "satisfactory" message.
 - processing completed

#### Intended Effect:
Always provide output for command - if diagnose command doesn't find problems, then it will print the following message:
```
Checking sampler transitions treedepth.
Treedepth satisfactory for all transitions.

Checking sampler transitions for divergences.
No divergent transitions found.

Checking E-BFMI - sampler transitions HMC potential energy.
E-BFMI satisfactory for all transitions.

Effective sample size satisfactory.

Split R-hat values satisfactory all parameters.

Processing complete, no problems detected.
```
#### How to Verify:
unit tests

#### Side Effects:
none.

#### Documentation:
updated cmdstan user's guide accordingly

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses: 
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
made requested changes to program output.
updated PR description - added example output for model which passes all diagnostics, assigned copyright to Columbia University.

**Comment by bob-carpenter** [comment]
For some reason, I didn't see that @syclik had already started reviewing this.  So take my input as an optional suggestion.  I just approved my change request so it won't block anything.

**Comment by mitzimorris** [comment]
@syclik - done making changes - please review.

discussed Rhat msg with Ben and Aki at today's Stan meeting.  using constant to allow for future changes.

**Comment by mitzimorris** [comment]
@syclik - are messages OK?

**Comment by syclik** [comment]
Sorry--I missed the original notification. Please feel free to ping me again if that happens. 

It's approved.

**Comment by mitzimorris** [comment]
@syclik - thanks!

**Pull request merged**
