### PR TITLE
Resolve some unused variable warnings

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

Resolves some unused variable warnings shown in `make build`

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by WardBrian** [comment]
@serban-nicusor-toptal This is getting an error from the quality gate I don't understand, could you take a look?

**Comment by serban-nicusor-toptal** [comment]
Hmh, weird, it's complaining about some regex I think:
```
java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
```

Checking ...

**Comment by serban-nicusor-toptal** [comment]
I think if we change that to: `.*'sprintf' is deprecated.*` will make the regex valid. I'm not entirely sure why it failed now tho.

**Comment by WardBrian** [comment]
Ok, the odd CI failures seem sorted. Mind giving this a review now @mitzimorris?

**Review by mitzimorris — APPROVED** [review]
lgtm!

**Pull request merged**
