### PR TITLE
Fix disabling precompiled headers properly

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Summary:

With clang, PRECOMPILED_HEADERS=false currently has no effect, the .hpp.gch files are still built. This fixes that problem.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
You can validate this by running

```
make build -j4
make examples/bernoulli/bernoulli
```
first with an empty make/local. The file `stan/src/stan/model/model_header.hpp.gch` should be there.

Then set `PRECOMPILED_HEADERS=false` and run

```
make clean-all
make build -j4
make examples/bernoulli/bernoulli
```

**Comment by WardBrian** [comment]
What makes this clang-specific? I believe the flag worked correctly for me when setting up the MacOS conda installation

**Comment by rok-cesnovar** [comment]
Yeah, its not clang-specific. I fixed the title. 

> I believe the flag worked correctly for me when setting up the MacOS conda installation

Do you mean disabling precompiled headers worked?

**Comment by WardBrian** [comment]
Yes. [This commit](https://github.com/conda-forge/staged-recipes/pull/15203/commits/29b00ecde151b4a2137d8003231fa32b57df3d69) was the first which passed their CI on MacOS

**Comment by rok-cesnovar** [comment]
Oh yeah, that will make it not build on "make build":

https://github.com/stan-dev/cmdstan/blob/develop/makefile#L117 and https://github.com/stan-dev/cmdstan/blob/develop/makefile#L247

It did still include it here when you compiled a model: https://github.com/stan-dev/cmdstan/blob/develop/make/program#L29
And that made make build .hpp.gch files then.

**Comment by WardBrian** [comment]
Oh, I think in the conda use case that's actually the best case scenario. The issue was if the PCH was compiled before install (e.g, when it was compiled on a different machine), but compiling it on first model compilation is good for later performance. 

So this would disable that?

**Comment by rok-cesnovar** [comment]
Huh, yeah :/

I am not familiar with conda, but you could build cmdstan and delete the model_header.hpp.gch file with PRECOMPILED_HEADERS on. But I am not sure if that works for you.

**Comment by rok-cesnovar** [comment]
What we could do as an alternative is not build the precompiled header on `make build` but always with the first model compilation. That would mean you need to remove the PRECOMPILED_HEADERS=false line.

**Comment by WardBrian** [comment]
I suppose it's a question of whether we want the intended behavior to be as it currently is (the flag is only for `make build`) or if it should never build the pch file. I can probably make the conda build work as you suggest, I wonder if others are assuming this behavior however.

**Comment by rok-cesnovar** [comment]
There is no real difference for users I guess. It only makes the installation more transferable. I dont see a use case of why it would matter that the PCH file is built on `make build`.

**Comment by WardBrian** [comment]
The CI is finishing up now but it seems like deleting the file as part of the conda build is just as good, so either change is fine

**Comment by rok-cesnovar** [comment]
Ok, cool. Lets leave it as is then if it works for you.

**Review by WardBrian — APPROVED** [review]

**Comment by rok-cesnovar** [comment]
Thanks Brian!

**Pull request merged**
