### PR TITLE
Add model compile information to stdout and csv

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

Addresses a part of #887 

Add models compile information (stanc version and flags used) to the stdout and CSV.

Example: 
```
data
  file = examples/bernoulli/bernoulli.data.json
init = 2 (Default)
random
  seed = 21139381 (Default)
output
  file = output.csv (Default)
  diagnostic_file =  (Default)
  refresh = 100 (Default)
stanc_version = stanc3 66c38187 (Unix)
stancflags = --warn-pedantic
```
```
# init = 2 (Default)
# random
#   seed = 21139381 (Default)
# output
#   file = output.csv (Default)
#   diagnostic_file =  (Default)
#   refresh = 100 (Default)
# stanc_version = stanc3 66c38187 (Unix)
# stancflags = --warn-pedantic
```

This should be included to make reproducing easier, especially with stanc optimization flag now available.

The tests will fail until https://github.com/stan-dev/stanc3/pull/598 and https://github.com/stan-dev/stan/pull/2932 are merged

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Rok Češnovar, Univ. of Ljubljana

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
for version 
```
bin/stanc --version
stanc3 8b086da (Unix)
```
these are the compiler options:
```
  --debug-lex                      For debugging purposes: print the lexer actions
  --debug-parse                    For debugging purposes: print the parser actions
  --debug-ast                      For debugging purposes: print the undecorated AST, before semantic checking
  --debug-decorated-ast            For debugging purposes: print the decorated AST, after semantic checking
  --debug-generate-data            For debugging purposes: generate a mock dataset to run the model on
  --debug-mir                      For debugging purposes: print the MIR as an S-expression.
  --debug-mir-pretty               For debugging purposes: pretty-print the MIR.
  --debug-optimized-mir            For debugging purposes: print the MIR after it's been optimized. Only has an effect when optimizations are turned on.
  --debug-optimized-mir-pretty     For debugging purposes: pretty print the MIR after it's been optimized. Only has an effect when optimizations are turned on.
  --debug-transformed-mir          For debugging purposes: print the MIR after the backend has transformed it.
  --debug-transformed-mir-pretty   For debugging purposes: pretty print the MIR after the backend has transformed it.
  --dump-stan-math-signatures Dump out the list of supported type signatures for Stan Math backend.
  --warn-uninitialized             Emit warnings about uninitialized variables to stderr. Currently an experimental feature.
  --warn-pedantic                  Emit warnings about common mistakes in Stan programs.
  --auto-format                    Pretty prints the program to the console
  --print-canonical                Prints the canonicalized program to the console
  --version                        Display stanc version number
  --name                           Take a string to set the model name (default = "$model_filename_model")
  --O Allow                        the compiler to apply all optimizations to the Stan code.
  --o                              Take the path to an output file for generated C++ code (default = "$name.hpp")
  --print-cpp                      If set, output the generated C++ Stan model class to stdout.
  --allow_undefined                Do not fail if a function is declared but not defined
  --include_paths                  Takes a comma-separated list of directories that may contain a file in an #include directive (default = "")
  --use-opencl                     If set, try to use matrix_cl signatures.
```

not sure that all of these options will result in there being an output csv file - for the ones that make sense, we need to make sure that this doesn't break any CSV header parsing that exists.

**Comment by mitzimorris** [comment]
is this ready for review?
or does this have to wait on https://github.com/stan-dev/stan/pull/2932 ?

**Comment by rok-cesnovar** [comment]
Waiting for that PR

**Comment by rok-cesnovar** [comment]
Thanks! This has to wait for 2932 in Stan, so this will not go in this release.

**Pull request merged**
