### PR TITLE
Issue/1250 dont compile deprecated util print

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submisison Checklist

- [ ] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

remove deprecated utility from CmdStan makefile target `build`

#### Intended Effect:

speed up the build process (a little)

#### How to Verify:

run:
```
make clean-all
make build
```

verify that no program `print` in  subdir `bin`.

#### Documentation:

Makefile comments.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):   Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
note that the makefile comments for developers provide info on how to compile `print`, should one so desire.

**Comment by WardBrian** [comment]
What's the reasoning for doing this now if the previous comment said it would be available until 3.0?

**Comment by mitzimorris** [comment]
watching cmdstan build on a slow machine is painful and I happened to be watching the console while `print` was being built.   overall, it doesn't matter one way or another.

**Comment by WardBrian** [comment]
I think we should either keep building it or go further and remove the code entirely. Keeping the code around but not building it by default seems like it would still break anyone's workflow who does still rely on it, but also not actually decrease the code surface area of the repo

**Pull request closed without merging**
