### PR TITLE
Update stansummary to use split, rank-normalized Rhat, ESS

### LINKED ISSUE #1263: Update stansummary to use new rhat diagnostic
#### Summary:

Stan PR https://github.com/stan-dev/stan/pull/3266 update Rhat statistic.
Change stansummary accordingly

#### Description:

~~Open questions:  change computation of ESS as well to match R-ecosystem bulk / tail estimates?~~

Adding `R_hat_bulk` and `R_hat_tail`;  no ESS_bulk/ESS_tale (as of yet)

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.34.1

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

Based on #1290, but tries to touch less of the code. This updates `stansummary_helper` to use `chainset` instead of `chains`, and updates the existing tests to match.

Ditto for `diagnose`, but there I just took the code whole-cloth from @mitzimorris' PR

#### Intended Effect:

Closes #1263 by adding the new metrics to stansummary

#### Side Effects:

 Stansummary no longer shows an ESS/s metric.

#### Documentation:

Will update https://mc-stan.org/docs/cmdstan-guide/stansummary.html if merged

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Simons foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by WardBrian** [comment]
I’d prefer to keep any further behavior changes in a separate PR. Copying over the tests seems easy, though

**Comment by mitzimorris** [comment]
on further consideration, comments re what console output should look like is an extremely low-priority issue, since the CSV files are the most-used (by CmdStanPy) output from this utility - so low-priority as to not be worth the effort.

**Comment by WardBrian** [comment]
New tests added -- one of them caught an existing issue where matrix outputs would have a different behavior with respect to `sig_figs` when requesting CSV output. I've fixed this.

**Comment by WardBrian** [comment]
Huh, it appears our formatting logic does not consistently select between scientific notation and between two different machines. That makes the test which checks against exact outputs impossible, so I've simplified

Probably worth investigating another time, though as you note, the console output is not the 'primary' product here.

**Review by mitzimorris — APPROVED** [review]
LGTM!
many many thanks for this!

**Pull request merged**
