### PR TITLE
Give examples for using the GPU version of cholesky

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Submisison Checklist

- [ ] Run tests: `./runCmdStanTests.py src/test`
- [ ] Declare copyright holder and open-source license: see below

#### Summary:

Contains some preliminary tests in examples for the GPU version of stan-math

#### Intended Effect:

Increase speed of the Cholesky by using the GPU

#### How to Verify:

to-do

#### Side Effects:

to-do

#### Documentation:

to-do

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by Stevo15025** [comment]
We have good preliminary results for the `big_gp` stan program

CPU version:

```
Gradient evaluation took 5.57601 seconds
1000 transitions using 10 leapfrog steps per transition would take 55760.1 seconds.
Adjust your expectations accordingly!
```
GPU version:

```
Gradient evaluation took 1.97909 seconds
1000 transitions using 10 leapfrog steps per transition would take 19790.9 seconds.
Adjust your expectations accordingly!
```

I've copied two other examples from the [GP examples](https://github.com/stan-dev/example-models/tree/master/misc/gaussian-process) and need to tweak them so they are the types of problems we would want on a GPU

**Comment by Stevo15025** [comment]
The GPU version of `big_gp` just finished
```
examples/big_gp/optim_GP_gpu sample data file=examples/big_gp/big_gp_test.Rdat
method = sample (Default)
  sample
    num_samples = 1000 (Default)
    num_warmup = 1000 (Default)
    save_warmup = 0 (Default)
    thin = 1 (Default)
    adapt
      engaged = 1 (Default)
      gamma = 0.050000000000000003 (Default)
      delta = 0.80000000000000004 (Default)
      kappa = 0.75 (Default)
      t0 = 10 (Default)
      init_buffer = 75 (Default)
      term_buffer = 50 (Default)
      window = 25 (Default)
    algorithm = hmc (Default)
      hmc
        engine = nuts (Default)
          nuts
            max_depth = 10 (Default)
        metric = diag_e (Default)
        stepsize = 1 (Default)
        stepsize_jitter = 0 (Default)
id = 0 (Default)
data
  file = examples/big_gp/big_gp_test.Rdat
init = 2 (Default)
random
  seed = 4062117952
output
  file = output.csv (Default)
  diagnostic_file =  (Default)
  refresh = 100 (Default)


Gradient evaluation took 2.03851 seconds
1000 transitions using 10 leapfrog steps per transition would take 20385.1 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 30: cov_exp_quad: sigma is 0, but must be > 0!
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 30: cov_exp_quad: sigma is 0, but must be > 0!
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

Iteration:  100 / 2000 [  5%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  300 / 2000 [ 15%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  500 / 2000 [ 25%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  700 / 2000 [ 35%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration:  900 / 2000 [ 45%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1100 / 2000 [ 55%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1300 / 2000 [ 65%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1500 / 2000 [ 75%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1700 / 2000 [ 85%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 1900 / 2000 [ 95%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 12636.7 seconds (Warm-up)
               11713.9 seconds (Sampling)
               24350.6 seconds (Total)
```

So about 6.76 hours. I believe @rtrangucci said the CPU version usually takes about 10 hours

**Comment by rok-cesnovar** [comment]
It is a start :) 

I am now trying to identify the execution times of everything that is executed (part by part). Will post as soon as I have something.

**Comment by Stevo15025** [comment]
To make this user visible we need to do two things

1. Tell the compiler we are using the gpu
> Using the `-DVIENNACL_WITH_OPENCL  -lOpenCL` flags

2. Use the ViennaCL version of the code

**Comment by rok-cesnovar** [comment]
Execution time percentages:

matrix product - ~33-35%
both inplace solves - ~33-35%
cholesky - ~20%
data transfers - <3%

The data transfers are especially encouraging, the rest can definitely can be tuned to give better results. Hopefully I will be able to run this on the GTX1070 tomorrow to see what we get on a high-end GPU.

**Comment by Stevo15025** [comment]
The matrix products are very promising!

I like having my dinky gpu since it gives a nice upper bound on the time. 

As for implementation, what if we did something like 

`#define STAN_WITH_VIENNACL 1`

In the .stan file? Could Stan parse that and include the correct compilation flags + an external variable?

**Comment by bob-carpenter** [comment]
As to builds, you want to coordinate with @seantalts and @syclik 

Great news that this is running end to end!

**Comment by seantalts** [comment]
Bob, I think Steve is asking if we can include something in the Stan language to turn GPU support on, is that right Steve?

Unrelatedly, I don't think we generally want to check in generated files (e.g. bernoulli.hpp).

**Comment by rtrangucci** [comment]
Yeah this is great! We can cut the number of computations for the first matrix production in half as both of the matrices are lower triangular. Does ViennaCL have a lower triangular multiply function?

Rob

**Comment by bob-carpenter** [comment]
Fine with me as long as we can figure out how to allow it to be turned off by default and also how we can have testing for it.  So I think Sean and Daniel (@seantalts and @sycklik) need to be involved.

**Comment by rok-cesnovar** [comment]
@rtrangucci sadly no, they do not have triangular multiply.

**Comment by syclik** [comment]
@Stevo15025, here are just some thoughts on the build:

- I don't think the Stan program should be changed. We can leave it alone and by default it will build using the standard compiler
- I think a `#define` may work in the code. If there's a particular `#define`, we can include and use the GPU-based code.
- The `#define` can be included either in the local make file or passed as some sort of make option from CmdStan (and RStan / PyStan)

I'll walk through your pull request, but a few things:
- remove the compiled binaries
- remove the generated hpp files
- remove the generated output (output.csv)
- call the `.Rdat` file a `.data.R` file (unless it's something different)
- I think we can remove the changes to `makefile` (you should stash changes in your local `make/local` file)

**Comment by Stevo15025** [comment]
> Bob, I think Steve is asking if we can include something in the Stan language to turn GPU support on, is that right Steve?

That is correct! Though if that is too invasive we can do something else. Was mostly throwing the idea out there.

> So I think Sean and Daniel (@seantalts and @sycklik) need to be involved.

Yes, 100%. I'm very interested in how you guys think we should do this.

My idea for the `#define STAN_WITH_VIENNACL 1` mostly comes from how, in ViennaCL, if you want to use the GPU backend you just place `#define VIENNACL_WITH_OPENCL 1` at the top of the file. I thought users could place the stan with vienna define in their stan program and we could parse that to do what we would like. But this is out of my realm so I would much rather do what you guys feel good about.

> @rtrangucci sadly no, they do not have triangular multiply.

@rok-cesnovar  Could we do this? I think we would want to only compute on warps/blocks that have no parts in the lower triangular? Otherwise we get thread divergence

Something like
```opencl

__kernel void lower_triangular_matmul(const unsigned int L, const unsigned int M,
__global unsigned int *a, __global unsigned int *b, __global unsigned int *c) {
 
   int i, j, k, bl, di;
 
   i = get_group_id(1) * get_local_size(1) + get_local_id(1);
   j = get_group_id(0) * get_local_size(0) + get_local_id(0);
   // This gets the bottom left index of the work group?
   bl = get_group_id(1) * get_local_size(1) + L;
  // get diagonal index on same row as bottom left of work group
   di = j * (L + 1)
   unsigned int temp = 0;
   // If bottom left of block is not in lower tri, exit
   if (bl > di) {
   
   } else { 
   // normal matmul
       for(k = 0; k<M; k++) {
           temp += a[j * M + k]* b[k * L + i] * (i < L && j < L);
       }
       c[j * L + i] = temp;
   }
}
 
```

I'm a little rusty so I apologize if that doesn't look right. It's getting late here so if I have time tmrw or the next day I'll try this out.

> I'll walk through your pull request, but a few things:

This branch was mostly made with the intention to prototype the gpu parts of math-stan and see how well the speed-ups did "in the wild". 
TODO:
- [ ] remove the compiled binaries
- [ ] remove the generated hpp files
- [ ] remove the generated output (output.csv)
- [ ] call the .Rdat file a .data.R file (unless it's something different)
- [ ] remove the changes to makefile (you should stash changes in your local make/local file)

> Great news that this is running end to end!

!!!

**Comment by Stevo15025** [comment]
@seantalts are we able to get a travis instance with a gpu?

**Comment by syclik** [comment]
I think the best shot we have is to use Jenkins. The Mac Pro has a GPU. Do you know if the library is available to use on that? 

For reference: http://stackoverflow.com/questions/29986942/continuous-integration-service-for-gpu-package

**Comment by Stevo15025** [comment]
I would cross reference what gpu your Mac has with the doc here. This is a list of the GPUs they have tested on

http://viennacl.sourceforge.net/doc/manual-introduction.html

**Comment by bob-carpenter** [comment]
We can buy more hardware to test and run this.

**Comment by bob-carpenter** [comment]
If not Travis, could we do something in AWS?  I have no idea how hard that would be, so that's a really big question mark at the end there.

**Comment by seantalts** [comment]
I think it'd be easiest to give it a shot on the Mac Pro first - it's not listed on the ViennaCL page but I suspect it will work.

**Comment by Stevo15025** [comment]
Trying out the lower triangular multiply I posted above (and fixing the missing `;`) all tests for stan-math pass

```
Running main() from gtest_main.cc
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from AgradRevMatrix
[ RUN      ] AgradRevMatrix.mat_cholesky
[       OK ] AgradRevMatrix.mat_cholesky (0 ms)
[ RUN      ] AgradRevMatrix.exception_mat_cholesky
[       OK ] AgradRevMatrix.exception_mat_cholesky (0 ms)
[ RUN      ] AgradRevMatrix.mat_cholesky_1st_deriv_small
[       OK ] AgradRevMatrix.mat_cholesky_1st_deriv_small (83 ms)
[ RUN      ] AgradRevMatrix.check_varis_on_stack_small
[       OK ] AgradRevMatrix.check_varis_on_stack_small (0 ms)
[ RUN      ] AgradRevMatrix.mat_cholesky_1st_deriv_large_gradients
[       OK ] AgradRevMatrix.mat_cholesky_1st_deriv_large_gradients (1241 ms)
[ RUN      ] AgradRevMatrix.check_varis_on_stack_large
[       OK ] AgradRevMatrix.check_varis_on_stack_large (0 ms)
[----------] 6 tests from AgradRevMatrix (1324 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test case ran. (1325 ms total)
[  PASSED  ] 6 tests.
```
@rok-cesnovar can you check out my code for the lower tri multiplication [here](https://github.com/stan-dev/math/blob/gpu_cholesky/stan/math/prim/mat/fun/ViennaCL.hpp#L32)? It took me one try to get it to work and I fail to believe that I'm that good.

Just started running the code for the `big_GP` example. Getting 

```
Gradient evaluation took 1.56463 seconds
1000 transitions using 10 leapfrog steps per transition would take 15646.3 seconds.
Adjust your expectations accordingly!
```

Since the previous gpu version's gradient took `1.97909` and the CPU version took `5.57601` we can hand wave an extrapolation. The current version is 26% faster than the previous GPU version so it should take about `18019` seconds as compared to `24350` (about 5 hours vs  6.7 hours)

Now that @rok-cesnovar has shown a nice way to push custom kernels to ViennaCL we should use BayesCL as well. That should push us below 5 hours pretty easily.

I'm probably going to bed soon, but tomorrow/Saturday I will

1. Clean up this PR
2. Clean up stan-math PR
3. Try to implement BayesCL ( @rok-cesnovar would it just putting it in the right format or do we need anything else?)
4. More testing ( Need to do the tests as @bgoodri mentioned)

**Comment by Stevo15025** [comment]
Also I graduate this weekend and will be in Chicago next week until Sunday so I may be MIA for a bit

**Comment by bob-carpenter** [comment]
Congratulations!

**Comment by bob-carpenter** [comment]
> Now that @rok-cesnovar has shown a nice way to push custom kernels to ViennaCL we should use BayesCL as well.

What is BayesCL?  I found a CRAN package for Gibbs:

https://cran.r-project.org/web/packages/bayesCL/bayesCL.pdf

**Comment by rok-cesnovar** [comment]
I named the first version of the library with our GPU implementations bayesCL (we used it in the Cholesky benchmark and didnt have any better idea that the name of the package that we made before that and also includes the Cholesky implementation). Naming things is hard :)

@Stevo15025 I will check your implementation and let you know. 
It is straightforward to replace the Cholesky_decomposition with our bayesCL. We do not need anything else (just use the example from the cholesky benchmark). 
I am working on implementing some other steps in our library (particulary the solves) and tweeking the viennacl but it is still a work in progress, I should have some results by the evening ( afternoon in your case :) ). The first thing that can easily be optimized is removing the copy of vcl_L to L as L is not needed after GPU computations. 

I do have the results for the GTX1070. It takes around 4 hours.

**Comment by mike-lawrence** [comment]
Just a heads-up that it's about $1/hr to run a [NVIDIA Tesla K80 on Google's compute engine](https://cloud.google.com/compute/docs/gpus/?hl=en_US).

**Comment by rok-cesnovar** [comment]
@Stevo15025 It seems that you commented out the cholesky_gpu in the commit and the non-gpu chain() function is called. Anyways, I tested the kernel function.

The only error is that you declared the inputs as pointers to int and not double and the temp variable should also be double. When I replaced that it passes the test. It is however not faster than the viennacl prod function.

**Comment by Stevo15025** [comment]
Yikes! Thanks for catching that. Can you post the code? I will fix that up when I get home

**Comment by rok-cesnovar** [comment]
Sure, [here](https://github.com/stan-dev/cmdstan/files/997314/kernel_lower_tri_mult.txt) it is. I put it in a file as its full of quatation marks. So far I have gotten the best results by using tiling and local/shared memory, but I am still not happy with it.

**Pull request closed without merging**
