### PR TITLE
check if bin exists and if not make it

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

adds `@mkdir -p $(dir $@)` before downloading the new compiler

#### Intended Effect:

`make build` works

#### How to Verify:

`make build`

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Steve Bronder

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by SteveBronder** [comment]
The current release of cmdstan is broken without this so I think we should do a 2.22.1

**Comment by bbbales2** [comment]
Looks like we ran into different problems: https://github.com/stan-dev/cmdstan/issues/804#issuecomment-578437045

I was installing cmdstan via cmdstanr. Dunno if that's why mine failed at a copy vs. yours failed at a download or not.

**Comment by bbbales2** [comment]
Yeah the .tgz contains all the different binaries and copies instead of downloading them. I hit this bug cause cmdstanr grabs the .tgz.

**Comment by SteveBronder** [comment]
Where are you seeing the .tgz at?

**Comment by wds15** [comment]
Would be good to find out how this glitch went into the release and how we prevent it next time.

**Comment by bbbales2** [comment]
@SteveBronder Thanks for getting the parenthesis too.

**Comment by SteveBronder** [comment]
> Would be good to find out how this glitch went into the release and how we prevent it next time.

Something something we need to fix make clean-all to remove /bin and have jenkins run `make build` and check for errors

**Comment by bbbales2** [comment]
It's platform and install-type sensitive too :D. On Linux make build worked fine for me. On Linux the .tgz did not.

**Comment by SteveBronder** [comment]
By .tgz you mean the release tarball?

I'm on ubuntu linux and it was not building for me with `make build`

**Comment by rok-cesnovar** [comment]
> Would be good to find out how this glitch went into the release and how we prevent it next time.

See the issue thread.

> we need to fix make clean-all to remove /bin

No no, This will break the way we do tarballs now, Cmdstan tarballs come with /bin/mac-stanc, /bin/windows-stanc and /bin/linux-stanc which ensures that tarball cmdstan will always use th stanc associated with the release (v2.22 currently).

**Comment by rok-cesnovar** [comment]
We need to make sure however we release this 2.22.1 or re-release of 2.22.0 that is only includes master + the merge commit of this PR. Otherwise, that release will also include all the stuff that was merged on Math since release.

**Comment by wds15** [comment]
that would be a lot of stuff...including a new sundials library... so, yes, this .1 release should be made as a change to cmdstan only.

**Pull request merged**
