### PR TITLE
Feature/update to writer callback

### PR DESCRIPTION
**Pull request by betanalpha**
#### Summary:

Updates corresponding to the Stan3 reorganization.  See https://github.com/stan-dev/stan/pull/1546.

#### Intended Effect:

Ensure consistency with the new API.

#### How to Verify:

All tests should eventually pass.

#### Side Effects:

None at the moment.

#### Documentation:

None at the moment.

#### Reviewer Suggestions: 

@syclik

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Shouldn't Jenkins be kicking off these tests automatically?

- Bob

**Comment by syclik** [comment]
Yes. I'll hunt it down.

**Comment by bob-carpenter** [comment]
Hmm.  Looks like it did kick off the tests, so why'd it ask us to verify?  Isn't that for when someone submits an outside pull request?

**Comment by syclik** [comment]
I'll need to hunt down why it's sending us that message. It has to be a
configuration issue.

**Comment by syclik** [comment]
Jenkins, ok to test.

**Comment by betanalpha** [comment]
We need some fixes before tests will pass anyways,
although Jenkins should just be giving us well-formatted
failure warnings...

**Pull request closed without merging**
