### PR TITLE
Bugfix/551 instantiate model with rng

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
Instantiate Stan Model object with specified random_seed value via 3-arg constructor

#### Intended Effect:
RNG functions in transformed data block will use same seed as used by sampler.

#### How to Verify:
Run test model  `src/test/test-models/transformed_data_rng_test.stan`  with data file `src/test/test-models/transformed_data_rng_test.init.R`:

- without specifying random seed, 2 successive runs (all default args, including output `output.csv`), will result in different estimates of params `mu`, `sigma`, `mean_y`, `sd_y`.

- when specifying same random seed, 2 successive runs result in identical estimates.

#### Side Effects:
Currently,  models which use RNG in transformed data block are all using RNG seed `0`.   May result in different behavoir of existing models.

#### Documentation:
None

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Mitzi Morris

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by seantalts** [comment]
Jenkins, retest this please.

**Comment by mitzimorris** [comment]
many thanks!

**Comment by mitzimorris** [comment]
let's not merge this until we have more discussion about how all interfaces should implement this feature.

**Comment by bob-carpenter** [comment]
Thanks for holding off on the merge.

**Comment by mitzimorris** [comment]
build will fail until Stan PR https://github.com/stan-dev/stan/pull/2313  is merged.

**Comment by mitzimorris** [comment]
Jenkins, retest this please

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by mitzimorris** [comment]
@seantalts or @syclik why is the Travis CI build failing?
is it a problem with the code or the config?

**Comment by mitzimorris** [comment]
@syclik - this hasn't yet been merged - could you please review?

**Comment by syclik** [comment]
Looks great! Did we ever have the discussion that you mentioned here? https://github.com/stan-dev/cmdstan/pull/552#issuecomment-301841022

**Comment by mitzimorris** [comment]
yes, changes to interfaces were discussed in a Stan meeting and have been implemented in RStan and PyStan.

**Pull request merged**
