### PR TITLE
Issue 565 Output a more descriptive error when missing submodule

### LINKED ISSUE #565: Better error messages if missing Stan submodule
#### Summary:
We'd like nice error messages if someone clones CmdStan without `--recursive`.

#### Reproducible Steps:
Clone CmdStan without the `--recursive` flag and end up missing the stan subdirectory and try to make an example.

#### Current Output:
```
Seans-MBP ~/scm/temp/cmdstan (build/c++11) $ make examples/bernoulli/bernoulli
makefile:29: stan/lib/stan_math/make/libraries: No such file or directory
makefile:34: stan/lib/stan_math/make/default_compiler_options: No such file or directory
makefile:52: stan/lib/stan_math/make/detect_cc: No such file or directory
makefile:62: stan/lib/stan_math/make/detect_os: No such file or directory
find: stan/src/stan/lang: No such file or directory
find: stan/src/stan/lang: No such file or directory
make: *** No rule to make target `stan/lib/stan_math/make/detect_os'.  Stop.
```

#### Expected Output:
Ideally something mentioning that they should make sure they update the submodules with `git submodule init; git submodule update --recursive` or to reclone with `git clone git@github.com:stan-dev/cmdstan.git --recursive`.

#### Current Version:
v2.16.0

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
Fixes #565 

This PR changes the behavior on make build when no Stan submodule is present.
It does this by checking for the existence of the stan/src folder.

It will now output:

```
make build
No stan/src folder found. Missing Stan submodule. Please run the following commands to fix 
 git submodule init
 git submodule update --recursive

g++    -c -o bin/cmdstan/stansummary.o src/cmdstan/stansummary.cpp
src/cmdstan/stansummary.cpp:5:10: fatal error: stan/mcmc/chains.hpp: No such file or directory
 #include <stan/mcmc/chains.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make/command:2: recipe for target 'bin/cmdstan/stansummary.o' failed
make: *** [bin/cmdstan/stansummary.o] Error 1
```

I am open to any suggestions regarding the new error message.

This PR also adds a "make stan-submodule-check" that outputs the same message if stan/src is not found.

This has to wait for the switch to stanc3. Its easier to implement once we switch, though its also doable now.

#### Intended Effect:

More descriptive error.

#### How to Verify:

Clone cmdstan without --recursive and try make build.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Rok Češnovar

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by serban-nicusor-toptal** [comment]
```
 1 FAILED TEST

test/interface/print_uninitialized_test --gtest_output="xml:test/interface/print_uninitialized_test.xml" failed
```


https://jenkins.mc-stan.org/blue/organizations/jenkins/CmdStan/detail/PR-738/2/pipeline/45

**Comment by rok-cesnovar** [comment]
Yeah, this is built on top of the stanc3-switch branch that needs a fix. This is outputting the same error.

**Comment by rok-cesnovar** [comment]
As note in the issue the current error after merge of stanc3 is actually that it cant detect the OS.

This PR will change the outputed error to:

```
~/Desktop/cmdstan$ make build
make/stanc:20: *** 
 ERROR: Missing Stan submodules. 
 Please run the following commands to fix: 

 git submodule init 
 git submodule update --recursive 

 Then try again.  Stop.
```
I am open to any suggestion to improve the text (The Stop. is somethin make adds because we use $(error .. ). This is not a critical thing for 2.21 since this is targeted at people that clone from github directly. Anyone using release tarballs is fine either way.

Also added newlines to the cant detect OS properly error:
```
make build
make/stanc:20: *** 
 Can't detect OS properly. 
 This will impede automatically downloading the correct stanc. 
 Please visit https://github.com/stan-dev/stanc3/releases and download a stanc binary for your OS and place it in ./bin/stanc.  Stop.
```

**Comment by seantalts** [comment]
The "Stop." there are the end is hilarious, hahaha. I'd say at least put a newline in between "Then try again." and "Stop." if you can, haha.

**Comment by rok-cesnovar** [comment]
Yeah. Try again. no no no I mean Stop. :hammer: 

If I put a newline at the end then it would be

```
Then try again
.  Stop.
```
because $(error also adds the dot. Will try to find out if i can remove the Stop. altogether.

**Comment by seantalts** [comment]
I would be happy with
```
And then try again.
.Stop.
```
or without the try again.

**Comment by rok-cesnovar** [comment]
Great, thanks! I am just now trying to get rid of the "Stop.". Will push the changes when I find an easy solution.

**Comment by mitzimorris** [comment]
@rok-cesnovar I feel your pain - makefiles suck!

**Comment by rok-cesnovar** [comment]
I managed to find a solution for this. The trick is to change the build target to just printing out a message if there are no submodules.
If that is fine, then this is good to go.
The error message now looks like this: 
```
ERROR: Missing Stan submodules.
Please run the following commands to fix:

git submodule init
git submodule update --recursive

And try building again
make: *** [makefile:192: build] Error 1
```

**Comment by seantalts** [comment]
Nice!

**Pull request merged**
