### PR TITLE
[CI] Ensure mac interface tests are running correctly on m1 instance

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
#### Submisison Checklist

- [ ] Run tests: `./runCmdStanTests.py src/test`
- [ ] Declare copyright holder and open-source license: see below

#### Summary:

WRT https://github.com/stan-dev/ci-scripts/issues/24 we've got a new M1 instance that we need to test our CI on to ensure everything is working fine.

#### How to Verify:

Results should be consistent with the older Mac Instance.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Toptal

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by serban-nicusor-toptal** [comment]
The initial problem was the missing `python` binary on the M1 instance.
After that was fixed, we seem to have a failing test
```
test/interface/stansummary_test --gtest_output="xml:test/interface/stansummary_test.xml" failed
```

**Comment by WardBrian** [comment]
Huh, it seems like the formatting/precision of the output numbers changed. They still look like the right values, just formatted differently. Odd behavior to see change like that

**Comment by WardBrian** [comment]
Huh, this might have found an actual bug with how we compute the width and precision of `nan`

**Comment by WardBrian** [comment]
@serban-nicusor-toptal I think I found the issue. Assuming it passes can do a run on all the machines to make sure it is consistent, but then I'll want someone (probably @rok-cesnovar) to take a quick look at the C++ changes I made

**Comment by rok-cesnovar** [comment]
Happy to do it.

**Comment by WardBrian** [comment]
Yep, that made it so CI matches my local (Ubuntu) results.

NaN values to the `calculate_width` function were previously returning `18446744071562067971`, which forced any column with an `nan` in it to be formatted as scientific notation. I think that the modern Clang library had a nicer implementation of the floating point standard which avoided this somehow. 

Explicitly treating `nan`s is the right thing to do, anyway.

**Comment by serban-nicusor-toptal** [comment]
Just wanted to note that this [commit](https://github.com/stan-dev/cmdstan/pull/1145/commits/58c7b2cc5eed94c16c5d3927a63f01dbcdeac981) is still happening, I think that's the plugin itself doing the merge. If we change the default we might affect other projects on Jenkins hmmh

**Comment by WardBrian** [comment]
Assuming the above run passes I think all we need to do is change the label from `m1` back to just `osx` and then merge.

@rok-cesnovar mind taking a look at the C++?

**Review by rok-cesnovar — APPROVED** [review]
C++ changes look good! Thanks both!

**Comment by WardBrian** [comment]
@serban-nicusor-toptal is there a reason we have multiple `recordIssues` in this repo and only one of them in `stan`? It seems like all of them collect warnings from all the platforms

**Comment by serban-nicusor-toptal** [comment]
The only reason for that is to have them visually separated, it makes it easier to debug and find targeted issues.
https://jenkins.flatironinstitute.org/job/Stan/job/CmdStan/job/develop/100/
vs
https://jenkins.flatironinstitute.org/job/Stan/job/Stan/job/develop/89/
Not sure why for Stan we went with a global one, maybe it's less to worry about ?
image

**Comment by WardBrian** [comment]
It looks like (based on https://jenkins.flatironinstitute.org/job/Stan/job/CmdStan/job/PR-1145/12/) that the Windows and Linux gates were failing due to the warnings that the Mac was generating but ignoring

**Comment by serban-nicusor-toptal** [comment]
Oh, that's unexpected, I was under the impression that it will treat them as different sources.
I think this is caused because of `aggregatingResults : true` 
``` 
aggregatingResults : boolean (optional)
By default, each static analysis result will be recorded as a separate result that is presented as an individual   
Jenkins Action with separate UI and dashboard. If you rather prefer aggregation of the results into a single result  
(i.e., single Jenkins Action), then activate this check box. You still can see the distribution of issues grouped by static analysis tool in the UI.
```
https://www.jenkins.io/doc/pipeline/steps/warnings-ng/
Which I think we want to be actually `false` in `cmdstan` case.

**Comment by WardBrian** [comment]
Sounds good. When that passes I think you can go ahead and squash and merge

**Pull request merged**
