### PR TITLE
diagnostics writer now has a nullptr if we are not using it

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

This needs to wait for https://github.com/stan-dev/stan/pull/3087 but fixes the performance regression in https://github.com/stan-dev/cmdstan/issues/1055

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by SteveBronder** [comment]
@rok-cesnovar once this goes in do we just make a PR to merge master into develop for the change? How do you feel about in the future just having a branch like `release/2.29` so that then in the future we can just merge bugfixes directly into the branch and then do another release off of it

**Comment by rok-cesnovar** [comment]
> @rok-cesnovar once this goes in do we just make a PR to merge master into develop for the change?

Yeah, I am making a checklist for the patch release just now. That will be the last item of it.

> How do you feel about in the future just having a branch like version/2.29 so that then in the future we can just merge bugfixes directly into the branch and then do another release off of it

I am good with that. That branch actually already exists: https://github.com/stan-dev/cmdstan/tree/v2.28.1

**Review by rok-cesnovar — DISMISSED** [review]

**Comment by rok-cesnovar** [comment]
@SteveBronder no need to update the submodule. That will happen once the Stan master tests pass: https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/master/30/pipeline/

**Comment by SteveBronder** [comment]
@rok-cesnovar I forgot the jenkins bot just updates develop so I just pushed this to update the stan repo to the current master in this PR

**Review by rok-cesnovar — APPROVED** [review]

**Pull request merged**
