### PR TITLE
Bugfix/577 diagnose rhat msg

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
Fixed error message to reflect what code is doing.

#### Intended Effect:
better diagnostics.

#### Side Effects:
none

#### Documentation:
N/A

#### Reviewer Suggestions: 
@syclik   @seantalts 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
#577

**Comment by jjramsey** [comment]
I'm surprised that this bugfix has yet to be merged in over 10 months.

**Comment by seantalts** [comment]
I don't think the tests are passing...

**Comment by mitzimorris** [comment]
thanks for the ping - will update and fix problem with unit tests.

**Comment by mitzimorris** [comment]
tests are passing - @seantalts or @syclik, please review when you get a chance

**Pull request merged**
