### PR TITLE
Pull stanc3 out of develop before 2.21 release

### PR DESCRIPTION
**Pull request by seantalts**
We still have some known bugs, and while we have less known bugs than the old compiler, at the meeting we all decided we should squash the known bugs and get more testing before releasing in 2.22.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
:/ I wasnt at the meeting so sorry if this was discussed but I feel like a `make stanc3` option would still make sense here to add some exposure to the new compiler and discover any other issues in t.me for 2.22

**Comment by seantalts** [comment]
Yeah, I think that was the plan from the meeting - once we / I fix the last few bugs in code gen we can merge back to develop.

We can put the revert of this on a branch and give easy instructions to change branches and recompile? Is that good enough?

**Comment by rok-cesnovar** [comment]
Yeah, definitely. Thanks!

**Comment by seantalts** [comment]
Same... I just think it's a bit rushed. But I think the process was correct - merging to develop on CmdStan is what enabled us to find all of these bugs in the first place. And it's nice I'm not pulling all nighters to fix them all before this afternoon, haha. So once those are all squashed it makes sense to merge back in to develop. Sorry for the setback especially for the GPU optimizations :(

**Pull request merged**
