### PR TITLE
Bugfix/641 make cmdstan manual

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submisison Checklist

- [ ] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
command `make manual` works on fresh install of cmdstan, stan.  Stan PR https://github.com/stan-dev/stan/pull/2694 fixed stan/make/manual so that directory `doc` is created for module's documentation suite.  this PR adds more cleanup to makefile.

#### Intended Effect:
make target `make manual` should build documentation suite

#### How to Verify:
run make

#### Side Effects:
none

#### Documentation:
none

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mitzimorris** [comment]
@seantalts or @syclik - how long does it take for merges to github to be picked up by circleci?  this fix depends on file `stan/make/manual`, but the circleci log looks like it's not seeing the changes.  retest later?

**Comment by seantalts** [comment]
Ah, merges to Stan? Hmm, let me try to manually re-run it... I'm not really sure, actually. We may also want to get rid of the circleci part if the book has been moved out...

**Comment by bob-carpenter** [comment]
The user's guide has been moved out, but not the functions reference and not the reference manual.

**Comment by mitzimorris** [comment]
@seantalts 

I'm looking at the circleci logs and task: `git submodule update --init --recursive` is checking out this stan submodule:

```
Submodule path 'stan': checked out 'dc01681e6e578ae539da82710dcf6eceb2b5de07'
``` 

why isn't it checking out latest develop:  `7ea40259c64a5fd90bd8b867e25afd6788ff22cc`?

**Comment by seantalts** [comment]
I guess it's testing the exact code in this PR, instead of the result of merging this PR with develop :( Would you mind merging in develop and pushing and seeing if that fixes it?

**Comment by mitzimorris** [comment]
> Would you mind merging in develop and pushing and seeing if that fixes it?

what is the git incantation to do this? trying to understand what's here: https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging , but like the unix man pages, you can only understand it once you already understand it.  :-(

**Comment by seantalts** [comment]
Oh you got it! Sweet.

**Comment by mitzimorris** [comment]
finally!!!!

**Comment by bob-carpenter** [comment]
$ git pull origin develop

will merge the current state of develop into your branch.  I think you need to wait for the CI to push up the changes to the downstream repos.

**Comment by mitzimorris** [comment]
@seantalts could you please approve PR on manual?

**Pull request merged**
