### PR TITLE
Fixing the makefiles

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
This pull request simplifies the build and gets the makefiles in order. The makefiles got tangled up through a few recent changes. This uses changes from the PR in Math: stan-dev/math#956, and the PR in Stan: stan-dev/stan#2601.

Here are some of the highlights:
- `CXX` is the only compiler setting used. In develop, both `CXX` and `CC` have to be set
- Windows: removed the `uname: not found` message
- `CXXFLAGS` are now broken into smaller components that can be set by the user:
    - `CXXFLAGS_LANG` for language-specific flags
    - `CXXFLAGS_WARNINGS` for ignoring warnings
    - `CXXFLAGS_BOOST` for boost-specific flags
    - `CXXFLAGS_SUNDIALS` for sundials-specific flags
    - `CXXFLAGS_EIGEN` for eigen-specific flags
    - `CXXFLAGS_GTEST` for google-test-specific flags
    - `CXXFLAGS_OS` for a catch-all and any os-specific flags.
- `CPPFLAGS` are broken into components (`CPPFLAGS` are the C preprocessor flags):
    - `CPPFLAGS_BOOST` for boost-specific flags
    - `CPPFLAGS_SUNDIALS` for sundials-specific flags
    - `CPPFLAGS_EIGEN` for eigen-specific flags
    - `CPPFLAGS_GTEST` for google-test-specific flags
    - `CPPFLAGS_OPENCL` for opencl

  breaking apart the flags this way makes it clearer how to extend the flags for MPI and GPU.
- each of the flags can be set within `make/local` and it will take precedence over the default values
- the dependency generation now generates with dummy targets for each file. This means more robustness in that -- this fixes problems where a header file is removed from the source tree. This caused a lot of trouble with stability of make.

#### Intended Effect:

This will get it so the makefiles shouldn't really need updating for a while. It's modular enough for extension with MPI or GPU or other will be simple.

#### How to Verify:

1. Run all tests. Everything should build. @bbbales2, I even got it so we can update one of the files in the parser and it'll rebuild the appropriate tests.
2. Verify that you can build a new Stan executable using these makefiles.

#### Side Effects:

We no longer use `CC`. This will have to be updated to `CXX`.

#### Documentation:

- [x] After this is working, update the wiki and the manual appropriately.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Generable

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Finally, the CmdStan make fixes. This should have dug us out of the technical debt we got into.

@wds15, can you check that the MPI stuff works? (You'll need to check out the Stan and Math branches first. And please make sure it's from a clean build. Also, I couldn't get MPI to work with develop.)

cc: @seantalts @mitzimorris @bob-carpenter

**Comment by bbbales2** [comment]
When I switched to clang (CXX=clang in make/local), I got these errors:

`
In file included from src/cmdstan/stanc.cpp:1:
In file included from stan/src/stan/command/stanc_helper.hpp:4:
stan/src/stan/version.hpp:4:10: fatal error: 'string' file not found
#include <string>
`

Which were symptomatic of the -stdlib=libc++ flag floating around.

Sean got rid of this flag here: https://github.com/stan-dev/math/pull/919

**Comment by syclik** [comment]
Can you try with clang++ instead of clang? If that's the same, let me know
what OS and whatever additional flags you needed to make it work. Thanks!

**Comment by bbbales2** [comment]
Ubuntu 16.04. If I set CXX=clang++ I get infinite build loops that look like:

`
~/cmdstan-make$ make clean
clang++ -std=c++11 -stdlib=libc++ -std=c++1y -Wno-sign-compare      -O3 -I src -I stan/src -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.66.0 -I stan/lib/stan_math/lib/sundials_3.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION     -c -MT stan/src/stan/model/model_header.hpp.gch -MT stan/src/stan/model/model_header.d -M -MG -MP -MF stan/src/stan/model/model_header.d stan/src/stan/model/model_header.hpp
`

even if I'm doing something like make clean (as shown)

I can give you an account on the computer I'm using if that'd be easy, but it's just a regular ol' out of date Ubuntu 16.04

**Comment by wds15** [comment]
+1 everything works out of the box for MPI.

@syclik ... MPI should work on the current develop as well by now; we merged some recent changes.

All I am putting into my `make/local` is

```
CXX=mpicxx
STAN_MPI=true
```

that's it.

**Comment by syclik** [comment]
Anyone want to review this? It should be merged with Math and Stan's PRs. But it'd be great to get it all in.

**Comment by mitzimorris** [comment]
I tested the rule to transpile models:
```
~/github/stan-dev/cmdstan/stan (bugfix/issue-2593-make)> make src/test/test-models/good/break-continue.hpp-test
find: stan: No such file or directory
find: stan: No such file or directory
c++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION     -c src/test/test-models/stanc.cpp -o test/test-models/stanc.o
c++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION      -c -o test/stan/lang/grammars/program_grammar_inst.o src/stan/lang/grammars/program_grammar_inst.cpp
c++ -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION      -c -o test/stan/lang/grammars/expression_grammar_inst.o src/stan/lang/grammars/expression_grammar_inst.cpp
src/stan/lang/grammars/expression_grammar_inst.cppsrc/test/test-models/stanc.cppsrc/stan/lang/grammars/program_grammar_inst.cpp:::111:::101010:::   fatal error: fatal error: fatal error: 'stan/lang/grammars/program_grammar_def.hpp' file 'stan/lang/grammars/expression_grammar_def.hpp'not 'stan/command/stanc_helper.hpp'file  notfile  foundnot 
found
 found
#include <stan/lang/grammars/expression_grammar_def.hpp>#include <stan/lang/grammars/program_grammar_def.hpp>#include <stan/command/stanc_helper.hpp>


         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1 error generated.
1 error generated.
make: *** [test/stan/lang/grammars/expression_grammar_inst.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [test/stan/lang/grammars/program_grammar_inst.o] Error 1
1 error generated.
make: *** [test/test-models/stanc.o] Error 1
```

history:
```
  500  git checkout bugfix/issue-2593-make 
  501  make clean-all
  503  ls src/test/test-models/good/b*
  504  make src/test/test-models/good/break-continue.hpp-test
```

did I miss something, or is this rule not working?

**Comment by syclik** [comment]
You'll need to update your math submodule manually to the correct branch.
bugfix/issue-954-make

Sorry about that -- I should have left that info on the top-level comment.
I'll update the PR later with that info.

Let me know if you run into any other problems! Or if that doesn't work.

**Comment by syclik** [comment]
Thank you!

**Comment by bbbales2** [comment]
I'm still getting:

```
$ touch stan/src/stan/lang/function_signatures.h 
$ make -j20 examples/bernoulli/bernoulli
g++ -std=c++1y -pthread -Wno-sign-compare     -O3 -I src -I stan/src -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.66.0 -I stan/lib/stan_math/lib/sundials_3.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION     -c -MT stan/src/stan/lang/ast_def.o -MT stan/src/stan/lang/ast_def.d -MM -E -MG -MP -MF stan/src/stan/lang/ast_def.d stan/src/stan/lang/ast_def.cpp
make: 'examples/bernoulli/bernoulli' is up to date.
```

I did a clean clone and updated all the submodules.

**Comment by bbbales2** [comment]
I forget how to surefire test this with Stan.

I thought it was working previously, but I'm trying to repeat that now and I get:
```
~/cmdstan-make2/stan$ make src/test/test-models/good/multiple_funs.hpp
g++ -std=c++1y -pthread -Wno-sign-compare     -O3 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.7.0/include -I lib/stan_math/lib/gtest_1.7.0     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -MT test/test-models/stanc.o -MT src/test/test-models/stanc.d -MM -MG -MP -MF src/test/test-models/stanc.d src/test/test-models/stanc.cpp
test/test-models/stanc src/test/test-models/good/multiple_funs.stan --o=src/test/test-models/good/multiple_funs.hpp
~/cmdstan-make2/stan$ touch src/stan/lang/function_signatures.h 
~/cmdstan-make2/stan$ make src/test/test-models/good/multiple_funs.hpp
make: 'src/test/test-models/good/multiple_funs.hpp' is up to date.
```

I looked through my bash history and I think that's the thing we were using at Stancon?

I also tried it with:
```
make src/test/test-models/good/funs1.hpp-test
```

Which didn't seem to respond to me touching function_signatures.hpp

**Comment by syclik** [comment]
Thanks for sending that example. I just pushed something because I realized I didn't include the dependencies for the `*.hpp-test` targets (in Stan).

The Stan repo is working for me. So the question is... what version of g++ are you on and why isn't it doing the right thing. And you're up to date with the branch for sure? 

Here's what happens on my machine:
```
$ make src/test/test-models/good/multiple_funs.hpp-test -j8
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I . -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.7.0/include -I lib/stan_math/lib/gtest_1.7.0 -I lib/stan_math/lib/gtest_1.7.0/include -I lib/stan_math/lib/gtest_1.7.0 -I lib/stan_math/lib/gtest_1.7.0/include -I lib/stan_math/lib/gtest_1.7.0       -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_USE_OWN_TR1_TUPLE  -c -o test/stan/lang/grammars/term_grammar_inst.o src/stan/lang/grammars/term_grammar_inst.cpp
...
ar: creating archive test/libstanc.a
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.7.0/include -I lib/stan_math/lib/gtest_1.7.0     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE         test/test-models/stanc.o        -Ltest -lstanc -o test/test-models/stanc
test/test-models/stanc src/test/test-models/good/multiple_funs.stan --o=src/test/test-models/good/multiple_funs.hpp
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION     -c -O0 -include src/test/test-models/good/multiple_funs.hpp test/dummy.cpp -o /dev/null
$ make src/test/test-models/good/multiple_funs.hpp-test -j8
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION     -c -O0 -include src/test/test-models/good/multiple_funs.hpp test/dummy.cpp -o /dev/null
$ touch src/stan/lang/function_signatures.h
$ make src/test/test-models/good/multiple_funs.hpp-test -j8
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O3 -I src -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION     -c -MT test/test-models/stanc -MT test/stan/lang/ast_def.o -MT src/stan/lang/ast_def.d -MM -MG -MP -MF src/stan/lang/ast_def.d src/stan/lang/ast_def.cpp
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I . -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.7.0/include -I lib/stan_math/lib/gtest_1.7.0 -I lib/stan_math/lib/gtest_1.7.0/include -I lib/stan_math/lib/gtest_1.7.0 -I lib/stan_math/lib/gtest_1.7.0/include -I lib/stan_math/lib/gtest_1.7.0       -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_USE_OWN_TR1_TUPLE  -c -o test/stan/lang/ast_def.o src/stan/lang/ast_def.cpp
ar -rs test/libstanc.a test/stan/lang/grammars/expression_grammar_inst.o test/stan/lang/grammars/program_grammar_inst.o test/stan/lang/grammars/var_decls_grammar_inst.o test/stan/lang/grammars/functions_grammar_inst.o test/stan/lang/grammars/whitespace_grammar_inst.o test/stan/lang/grammars/term_grammar_inst.o test/stan/lang/grammars/statement_2_grammar_inst.o test/stan/lang/grammars/expression07_grammar_inst.o test/stan/lang/grammars/indexes_grammar_inst.o test/stan/lang/grammars/bare_type_grammar_inst.o test/stan/lang/grammars/statement_grammar_inst.o test/stan/lang/grammars/semantic_actions_def.o test/stan/lang/ast_def.o
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I . -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include -I lib/stan_math/lib/gtest_1.7.0/include -I lib/stan_math/lib/gtest_1.7.0     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE         test/test-models/stanc.o        -Ltest -lstanc -o test/test-models/stanc
test/test-models/stanc src/test/test-models/good/multiple_funs.stan --o=src/test/test-models/good/multiple_funs.hpp
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION     -c -O0 -include src/test/test-models/good/multiple_funs.hpp test/dummy.cpp -o /dev/null
```

I'll make sure it works for CmdStan.

**Comment by bbbales2** [comment]
Same behavior.

```
~/cmdstan-make2/stan$ touch src/stan/lang/function_signatures.h
~/cmdstan-make2/stan$ make src/test/test-models/good/multiple_funs.hpp-test
g++ -std=c++1y -pthread -Wno-sign-compare     -O0 -I src -I lib/stan_math/ -I lib/stan_math/lib/eigen_3.3.3 -I lib/stan_math/lib/boost_1.66.0 -I lib/stan_math/lib/sundials_3.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION     -c -o /dev/null -include src/test/test-models/good/multiple_funs.hpp test/test-model-main.cpp
```

gcc version 5.4.0, last commit:

```
commit 7b00e8e546dbf31044732a0660782c9e89c0c940
Author: Daniel Lee <daniel@generable.com>
Date:   Fri Sep 7 14:45:06 2018 -0400

    including the dependencies for the Stan model tests: *.hpp-test
```

**Comment by syclik** [comment]
Just to make sure, math is at this commit?
commit c3a6a449be94e4430457134cf96b563026b15b4a
Author: Daniel Lee <daniel@generable.com>
Date:   Thu Aug 30 11:16:40 2018 +0300

    fixing a problem with an earlier merge

**Comment by syclik** [comment]
@bbbales2, it should be good now.

Just FYI, the targets have changed a bit. The test is now:
```
$ touch src/stan/lang/function_signatures.h
$ make test/test-models/good/multiple_funs.hpp-test
```

Drop the `src/`. I had to do this to play nicely on both Windows and Mac. I think.

**Comment by syclik** [comment]
Woo hoo! The tests pass. (Travis CI won't pass until everything is merged, so this is ok.)

**Comment by bbbales2** [comment]
It does seem to be behaving now, but I'm not sure it was the clean deps, sigh.

**Comment by syclik** [comment]
This is working too. Anyone want to take a look?

**Pull request merged**
