### PR TITLE
Feature/intel tbb init

### PR DESCRIPTION
**Pull request by wds15**
#### Submisison Checklist

- [ ] Run tests: `./runCmdStanTests.py src/test`
- [X] Declare copyright holder and open-source license: see below

#### Summary:

This initialises the TBB threadpool. 

#### Intended Effect:

Integrate with the Intel TBB in math.

#### How to Verify:

The test `src/test/interface/tbb_threadpool_test.cpp` verifies that initialisation of the threadpool is successful. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Sebastian Weber

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by wds15** [comment]
@rok-cesnovar Do you have any clue what is going with Windows here?

If you build this PR with parameters and use the math PR-1376 then it *should* work... but it doesn't. The thing is that all the tests get build correctly and then when the scripts try to execute the tests some failure happens. I think that the PATH variable is not set correctly - this is my only explanation I have at the moment.

Any ideas @rok-cesnovar ?

To be clear for everyone else: The unit tests do run just fine for math with the TBB! So it gotta be a config issue here. I don't have any other explanation.

I would appreciate any ideas on this ... @seantalts / @serban-nicusor-toptal ?

Thanks! Sorry for the rush, but it would hurt seeing all of this being pulled off at this stage.

**Comment by rok-cesnovar** [comment]
I have the EC2 win instance running and will start working on it in an hour. I am out right now.

**Comment by seantalts** [comment]
Can you post the error?

**Comment by wds15** [comment]
Look here:

https://jenkins.mc-stan.org/blue/organizations/jenkins/CmdStan/detail/PR-743/19/pipeline/43/

I don't see any error.

**Comment by wds15** [comment]
So we need to fix this and we apparently also need to reconfigure the performance tests suite. There the correct make must be used on Windows and the PATH has to be managed as well. Both is not yet in place.

**Comment by wds15** [comment]
For Windows you must have:

- use mingw32-make to build things
- add to the PATH variable the directory with the TBB library

otherwise it will just fail.

**Comment by rok-cesnovar** [comment]
Do performance tests have a separetu python that runs them? In that case that probably uses regular make on Windows

**Comment by seantalts** [comment]
> EDIT: both is outside of the control of CmdStan IF these things are not triggered by scripts part of CmdStan which is the case for the performance tests as I understand.

I thought we were adding the necessary bits to `make`?

**Comment by wds15** [comment]
the makefiles are updated, yes... but the Intel TBB makefiles require you that you use the make variant `mingw32-make` on Windows. We all agreed on that this is fine. This make is part of RTools and is on our Windows instances.

**Comment by wds15** [comment]
Correct. And you need to set the PATH variable to include

`cmdstan-root/stan/lib/stan_math/lib/tbb`

otherwise the binary TBB libs are not found when starting the executables.

we have created a `make install-tbb` target which sets this up for the user (permanently)... but that's not an option for performance tests.

**Comment by seantalts** [comment]
I thought we were also going to make sure the path is set if a user is using make? Like setting the user path before building any models.

**Comment by wds15** [comment]
That does not help you at all - the make is a sub-process. You need the PATH being set once the user calls the model. The PATH can be whatever during the build process.

**Comment by seantalts** [comment]
Agreed, but it could adjust the user's path automatically forever right? I
basically thought we were going with a solution that didn't break backwards
compatibility for this one since there were a few different options
(symlinking, copying, and path adjustments).

**Comment by wds15** [comment]
path adjustments are permanent, yes.

If you prefer symlinks on Windows - we can do that, of course. I don't trust symlinks on this OS...

**Comment by rok-cesnovar** [comment]
Can someone point me to where do I change which math branch this uses?

**Comment by rok-cesnovar** [comment]
For the test offcourse

**Comment by seantalts** [comment]
Near the bottom of the top post in here: https://discourse.mc-stan.org/t/new-jenkins-jobs-tutorial/2383

**Comment by wds15** [comment]
@rok-cesnovar I think I will be able to rewrite the makefile to do the following on Windows:

- check if tbb.dll is found on the PATH
- in case tbb.dll is NOT found then we copy the tbb.dll into the directory of the model

symlinks are not possible for non-admin users. This will give users the possibility to fix their config and lazy users pay with storage.

I am close to this... does this sound like a solution to you?

**Comment by wds15** [comment]
It works:

https://github.com/stan-dev/cmdstan/pull/744

This makes the PR under Windows fully backwards compatible at the expense of some disk space (5MB for the tbb.dll). Once the user sets up the PATH, then no more copying is being done.

I am not sure how we merge all this.

**Comment by rok-cesnovar** [comment]
That sounds good. I am trying to debug locally and on the EC2 machine, got nowhere. Pushed basically a stab in the dark to the branch (use make after build).

One thing I did notice is that if I run
mingw32-make build

and then run python runCmdStanTest.py src...

TBB files are getting built again. That is probably not expected behavior, right?

Sidenote: The runCmdStanTests.py needs a refactor, I found that under specific cases things dont work on Windows even if I checkout a commit before we started working on TBB. But that is for another day. Will definitely open issues once the dust settles on TBB and 2.21.

**Comment by wds15** [comment]
No - the rebuilding of the TBB is not expected - and the TBB is not rebuild if you first do `mingw32-make build` and then a `make examples/bernoulli/bernoulli.exe`.

I really hope that #744 passes so that all the other stuff can finally land.

**Comment by rok-cesnovar** [comment]
So do I. The test queue is quite full at the moment, so not sure we are going to get that feedback today.

**Comment by wds15** [comment]
Yup... Windows is a major bottleneck.

**Comment by serban-nicusor-toptal** [comment]
I've increased a bit the windows machines cap for now.

**Comment by rok-cesnovar** [comment]
I think they got stuck, a few Windows tests are stuck after finishing.

**Comment by wds15** [comment]
The other pr turned green

**Comment by rok-cesnovar** [comment]
Fantastic! I would go ahead and approve and merge that one and then restart 1376. Which would mean that one should be green tomorrow. We can then fix this one (revert my changes and changes to the Jenkinsfile). This PR isnt an issue anyways with the quick turnaround. Agree?

**Comment by rok-cesnovar** [comment]
Ah no, it seems that it didnt help actually...

**Comment by wds15** [comment]
Yeah...wrong...sorry.

**Comment by rok-cesnovar** [comment]
I will try again tomorrow on my lab Win machine. This is almost certainly something with the configuration. Tried 2 win machines just now, both look fine.

**Comment by wds15** [comment]
I guess we have to wait with this one until the math PR-1376 updates percolates up the repositories.

**Comment by rok-cesnovar** [comment]
> I guess we have to wait with this one until the math PR-1376 updates percolates up the repositories.

If the test pass, we have the right submodule, otherwise it would not find the threadpool init function.

**Comment by wds15** [comment]
Yes, that's right. If tests are good, then this can go in. The threadpool_init is called, so it will segfault. I am still confused that it just worked. Let me check what Stan-math we refer to.

**Comment by wds15** [comment]
let's wait a bit. The math ref is not yet up to date... I really wonder what is being tested here.

@seantalts Do you know which stan / math refs are being tested by Jenkins? It look to me as if the current develop is tested and NOT the referred to versions. That would be odd to me.

So the tests for this PR cannot pass until math is bumped to include PR-1376 which is not yet the case on cmdstan develop.

Is this a feature or a bug of our testing pipeline?

Maybe @serban-nicusor-toptal knows?

**Comment by rok-cesnovar** [comment]
I think this refers to whatever is on develop at the start of test. It doesnt wait for things to pass on develop to start refering to them. I think that doesnt sound unreasonable.

**Comment by rok-cesnovar** [comment]
This test had no build parameters so its definitely whatever is on develop.

**Comment by wds15** [comment]
Ok.. but then we definitely need to wait. If we would merge this now, then we break develop of CmdStan.

**Comment by rok-cesnovar** [comment]
I am not really sure how this could break develop. But I am also completely fine waiting for a few more hours just to be sure we dont need to go over this again.

So math develop should go green then Stan update submodule happens then that goes green and update the Cmdstan submodule and then go.

**Comment by wds15** [comment]
Maybe the tests on Jenkins would even be ok... but only because these run with the references to the latest develop. However, if you merge this now and someone downloads it, then the person will get a Stan-math as a dependency which does not yet include PR-1376 in math - and hence it will break.

**Pull request merged**
