### PR TITLE
Add argument to only output some parameters from `stansummary`

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

This adds an argument `--include_param` to `stansummary` which changes the behavior of the command to only calculate/output stats for the passed parameters.

For example, here is the existing output on the eight schools model:
```shell
$ ./bin/stansummary src/test/interface/example_output/eight_schools_output.csv
Inference for Stan model: eight_schools_cp_model
1 chains: each with iter=(1000); warmup=(0); thin=(1); 1000 iterations saved.

Warmup took 0.12 seconds
Sampling took 0.10 seconds

                   Mean     MCSE   StdDev     5%   50%   95%    N_Eff  N_Eff/s    R_hat

lp__                -16     0.97      6.1    -25   -16  -5.5       39      373      1.0
accept_stat__   9.2e-01  2.4e-02  1.8e-01   0.46  0.99  1.00  5.7e+01  5.5e+02  1.0e+00
stepsize__      1.2e-01      nan  6.2e-16   0.12  0.12  0.12      nan      nan      nan
treedepth__     4.3e+00  1.2e-01  9.4e-01    3.0   4.0   6.0  6.4e+01  6.2e+02  1.0e+00
n_leapfrog__    3.0e+01  1.8e+00  1.9e+01    7.0    31    63  1.2e+02  1.2e+03  1.0e+00
divergent__     7.0e-03  3.8e-03  8.3e-02   0.00  0.00  0.00  4.8e+02  4.6e+03  1.0e+00
energy__        2.1e+01  1.0e+00  6.4e+00     10    21    31  4.0e+01  3.9e+02  1.0e+00

mu                  6.1     0.37      4.3  -0.78   6.3    13      134     1293     1.00
tau                 4.7     0.53      3.9   0.78   3.6    12       53      514      1.0
theta[1]            8.4     0.60      6.6  -0.75   7.7    20      121     1168      1.0
theta[2]            6.5     0.39      5.5   -1.9   6.5    15      199     1917     1.00
theta[3]            5.4     0.34      6.1   -5.1   5.8    14      314     3022     1.00
theta[4]            6.4     0.35      5.7   -2.5   6.5    16      259     2496     1.00
theta[5]            4.5     0.37      5.7   -5.6   4.9    13      239     2295     1.00
theta[6]            5.0     0.37      5.8   -5.0   5.2    14      249     2396      1.0
theta[7]            8.5     0.65      6.2  -0.84   8.1    19       92      881     1.00
theta[8]            7.0     0.48      6.9   -4.2   7.0    18      211     2028     1.00

Samples were drawn using hmc with nuts.
For each parameter, N_Eff is a crude measure of effective sample size,
and R_hat is the potential scale reduction factor on split chains (at 
convergence, R_hat=1).
```

Here it is filtered to just theta[6]

```shell
$ ./bin/stansummary src/test/interface/example_output/eight_schools_output.csv --include_param theta.6
Inference for Stan model: eight_schools_cp_model
1 chains: each with iter=(1000); warmup=(0); thin=(1); 1000 iterations saved.

Warmup took 0.12 seconds
Sampling took 0.10 seconds

                   Mean     MCSE   StdDev    5%   50%   95%    N_Eff  N_Eff/s    R_hat

lp__                -16     0.97      6.1   -25   -16  -5.5       39      373      1.0
accept_stat__   9.2e-01  2.4e-02  1.8e-01  0.46  0.99  1.00  5.7e+01  5.5e+02  1.0e+00
stepsize__      1.2e-01      nan  6.2e-16  0.12  0.12  0.12      nan      nan      nan
treedepth__     4.3e+00  1.2e-01  9.4e-01   3.0   4.0   6.0  6.4e+01  6.2e+02  1.0e+00
n_leapfrog__    3.0e+01  1.8e+00  1.9e+01   7.0    31    63  1.2e+02  1.2e+03  1.0e+00
divergent__     7.0e-03  3.8e-03  8.3e-02  0.00  0.00  0.00  4.8e+02  4.6e+03  1.0e+00
energy__        2.1e+01  1.0e+00  6.4e+00    10    21    31  4.0e+01  3.9e+02  1.0e+00

theta[6]            5.0     0.37      5.8  -5.0   5.2    14      249     2396      1.0

Samples were drawn using hmc with nuts.
For each parameter, N_Eff is a crude measure of effective sample size,
and R_hat is the potential scale reduction factor on split chains (at 
convergence, R_hat=1).
```

You can use either `theta.6` or `theta[6]`, both are supported.  You can also pass the parameter multiple times, like `--include_param theta.6 -i theta.7` to display more than one.

Note: at the moment this still reads _all_ the draws, so it doesn't really help if you have larger-than-memory outputs. That's a future extension which is possible, though.

#### Documentation:

Documentation PR TDB

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by WardBrian** [comment]
This idea was spawned from a recent conversation with @bob-carpenter for a model which had 65k parameters, and how it would be useful to subset them in stansummary

**Comment by WardBrian** [comment]
I believe the test failures on MacOS are unrelated to this PR. We've had a bit of a nightmare this week with CI failures

**Comment by WardBrian** [comment]
I've changed the argument from `--model_param` to `--include_param,-i` and added information to the help output about how to use it

**Comment by serban-nicusor-toptal** [comment]
Hey @WardBrian for the warning we have two ways to approach it, either `excludeCategory('deprecated-declarations')` or `excludeMessage("*'sprintf' is deprecated*")`, I think we can both agree on the 2nd one so I've pushed a commit with it.
I couldn't get it to work based on a file sadly as it comes empty or `-`.

**Review by mitzimorris — APPROVED** [review]
LGTM!

**Pull request merged**
