### PR TITLE
cmdstan now triggers the performance job 

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
#### Submisison Checklist

- [ ] Run tests: `./runCmdStanTests.py src/test`
- [ ] Declare copyright holder and open-source license: see below

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by serban-nicusor-toptal** [comment]
Working on the #692 
Do not merge yet.

**Comment by bob-carpenter** [comment]
"highly illogical" is both insulting and vague.  Is there a way to produce a better message?

**Comment by serban-nicusor-toptal** [comment]
> "highly illogical" is both insulting and vague. Is there a way to produce a better message?

Good morning Bob,

As stated above this is a work in progress. That message is just to test a Jenkins plugin.
My comment states clearly that I'm working on #692 .

The desired output will look like this:

```
+ ./comparePerformance.py develop_performance.csv performance.csv
('stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr.stan', 0.99)
('stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss.stan', 0.96)
('stat_comp_benchmarks/benchmarks/eight_schools/eight_schools.stan', 0.99)
('stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.stan', 1.01)
('stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.stan', 1.0)
('performance.compilation', 1.42)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix_collapse/low_dim_gauss_mix_collapse.stan', 1.33)
('stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs.stan', 0.99)
('stat_comp_benchmarks/benchmarks/sir/sir.stan', 0.94)
('stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.stan', 1.17)
('stat_comp_benchmarks/benchmarks/garch/garch.stan', 1.08)
('stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data.stan', 1.0)
('stat_comp_benchmarks/benchmarks/arK/arK.stan', 0.92)
('stat_comp_benchmarks/benchmarks/arma/arma.stan', 1.01)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.stan', 0.97)
1.04474708074
```

**Comment by wds15** [comment]
+1

**Pull request merged**
