### PR TITLE
Test dedupe - for now we run os x tests on Jenkins.

### PR DESCRIPTION
**Pull request by seantalts**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary
Test dedupe - for now we run os x tests on Jenkins.
And as Travis is the slowest part of Stan builds, we'll cut off the OS X builds to save time
and get feedback to developers sooner. They're still covered by the Jenkins tests.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Dual Space LLC

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Looks like we don't have the strict code review guards in place on this repo.  Mind adding that like for the other ones?  And I think @syclik or @mitzimorris should review this one if you want someone else to look at it.  Looks fine to me.

**Comment by syclik** [comment]
Yes, we don't have the strict guards. We can add them pretty easily and I think you're right: we should have them in place.

**Comment by seantalts** [comment]
What are the guards you guys are talking about?

**Comment by syclik** [comment]
Protected branches. I just added some things, but I think it's not quite
there yet.

**Pull request merged**
