### PR TITLE
Add additional compiler optimization flags

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

This adds extra compiler flags for clang/gcc versions that can help speedup Stan models. These should help fix the regression we had in ODE models from add a template to vari.

#### Intended Effect:

For particular compiler versions and types we can add certain compile and link time flags to cmdstan and program compilation. Users have the option to turn all of these off by defining the flag `STAN_NO_COMPILER_OPTIMS`

#### How to Verify:

Will run by default for compilers that are set, however we mostly test on clang-6 and gcc-4.9. These optimizations purposefully do not add flags to these versions because of difficulties with compiling while using flto

#### Side Effects:

This will most likely lead to slightly longer compiler times, for some machines with multiple cores `flto` should alleviate some of that additional time

Also `CXX_TYPE` is defined in the math makefiles, but I ported it to up here because we want to set the make flags before we setup the rules for compiling the rest of Stan.

#### Documentation:

Documentation for each make variable is defined in the math library makefiles

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Steve Bronder

### CODE REVIEW

**Comment by SteveBronder** [comment]
@wds15 can you run the logistic regression example you were talking about? Or send it to me and I'll run it

**Comment by rok-cesnovar** [comment]
@SteveBronder I think this is changing the stan math submodule. Can you fix that and then this is good to go. Is LTO not feasible on windows even with RTools 4?

**Comment by wds15** [comment]
I can run the example, yes.

**Comment by wds15** [comment]
Hmm... I tried 2.24.1 (no speed issue), then develop and then this branch - but the performance regression still seems to be there. However, I haven't noticed a "lto" flag pop-up. Here are the timings:

```R
> ## 2.24.1
> new_time
   user  system elapsed 
 43.967   0.152  44.184 
> ## current develop
> dev_time
   user  system elapsed 
 46.521   0.202  47.773 
> ## this PR
> fixed_time
   user  system elapsed 
 47.258   0.190  48.243 
> 
```

Model and data is here:

[blrm_exnex_data_R.txt](https://github.com/stan-dev/cmdstan/files/5167599/blrm_exnex_data_R.txt)
[blrm_exnex_stan.txt](https://github.com/stan-dev/cmdstan/files/5167600/blrm_exnex_stan.txt)

**Comment by SteveBronder** [comment]
> @SteveBronder I think this is changing the stan math submodule. Can you fix that and then this is good to go. Is LTO not feasible on windows even with RTools 4?

tbh I just don't have a machine to test it on. I found that with lto and rtools 4.0 I was seeing an internal compiler error in jenkins when I turned on lto so I'd rather not touch it till I investigate more.

I'll fixup the math thing now.

@wds15 what compiler are you using? for clang++  flto will only turn on for version 8 or greater. For gcc it's version 7 or greater. tl;dr there's no easy way to check whether you are on clang-6 or clang-7 and clang-6 requires using the `llvm-ar`. There's a bug in gcc's flto that can pop up for gcc < 7 so I'd rather avoid the possiblity users see it. We could add something to the readme or a warning like

```
If you are using clang-6 or clang-7 we cannot automatically turn on lto. If you would like to use Stan with lto please add the below to a make/local
CXXFLAGS_FLTO = -flto=full -fwhole-program-vtables -fstrict-vtable-pointers -fforce-emit-vtables
# if using clang-6
AR=llvm-ar-6.0
```

Is it possible for you to email me the model?

**Comment by wds15** [comment]
I am on macOS Catalina. The clang++ --version gives me:

```
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by SteveBronder** [comment]
Odd, so I'm running

```
make clean-all
make -j4 build
make examples/blrm_exnex/blrm_exnex
test_function() {
for i in {1..10}; do \
  examples/blrm_exnex/blrm_exnex sample num_samples=5000 num_warmup=5000 data file=examples/blrm_exnex/blrm_exnex.data.R; \
done
}
time -p test_function
```

for each branch and I'm getting  for the total 10 runs

```R
PR:
real 313.05
user 309.74
sys 1.86

fa449c5:
real 307.48
user 306.17
sys 1.01

develop:
real 289.76
user 288.57
sys 0.97
```

So on average over the 10 runs

```R
PR: 31.3
fa449c5: 30.7
develop: 28.9
```

So on my machine it looks like develop is actually the best? and this PR is doing worse for some reason? I'm using gcc-8 , debian 10, and an intel-i7 with 2 cores. Can you report back the times from multiple runs?


I'm going to go back and test this out for sir later.

**Comment by wds15** [comment]
Can u fix the seed and always run chain id = 1?

**Comment by SteveBronder** [comment]
Yeah sure, also what do you get from `clang++ -dumpversion`

**Comment by wds15** [comment]
I get

```
[16:27:23][sebi@Sebastians-MBP-1:~/work/brms-parallel]$ clang++ -dumpversion
11.0.3
```

**Comment by SteveBronder** [comment]
So running 

```
  examples/blrm_exnex/blrm_exnex sample num_samples=5000 num_warmup=5000 data file=examples/blrm_exnex/blrm_exnex.data.R id=1 random seed=123
```

I'm getting

```R
PR:
real 317.77 (31.7 per run)
user 313.66
sys 1.98

fa449c5:
real 276.19 (27.6 per run)
user 274.80
sys 0.93

develop:
real 275.57 (27.5 per run)
user 274.45
sys 0.93
```

I'm on my dinky little laptop though, I can try this on my big desktop when I get back to nyc. I'll try this with clang as well

**Comment by SteveBronder** [comment]
That's odd since `echo "11.0.3" | cut -d'.' -f1` does give back "11" and we just use an if check to see if the major version is greater than 5. I'll take a look at this

**Comment by wds15** [comment]
Any life here?

**Comment by SteveBronder** [comment]
Running this right now. Tho' for the model you posted on develop/2.24.1 and running the model 10 times like

```stan
test_function() {
 for i in {1..10}; do \
  examples/blrm_exnex/blrm_exnex sample num_samples=5000 num_warmup=5000 data file=examples/blrm_exnex/blrm_exnex.data.R id=1 random seed=123${i}; \
done
}
```

I'm getting

```R

## Develop
real 162.57 (16.25 seconds for each)
user 161.54
sys 0.78

## 2.24.1
real 157.98 (15.79 seconds for each)
user 157.34
sys 0.51


16.25/15.79 = 1.0291 ~2% slower
```

I feel like 2% is, fine'ish. gonna run this PR rn

**Comment by SteveBronder** [comment]
Alright so for the SIR model on my machine with this branch I'm getting

## gcc

---RESULTS---
| Name | Old Result | New Result | Ratio | Performance change( 1 - new / old ) |
| ------------- |------------- | ------------- | ------------- | ------------- |
| stat_comp_benchmarks/benchmarks/sir/sir.stan | 65.06 | 47.54 | 1.37 | 26.93% faster |
| performance.compilation | 55.7 | 61.38 | 0.91 | -10.21% slower |
Mean result: 1.13791960906
---RESULTS---


## clang

---RESULTS---
| Name | Old Result | New Result | Ratio | Performance change( 1 - new / old ) |
| ------------- |------------- | ------------- | ------------- | ------------- |
| stat_comp_benchmarks/benchmarks/sir/sir.stan | 65.06 | 50.19 | 1.3 | 22.86% faster |
| performance.compilation | 55.7 | 52.29 | 1.07 | 6.11% faster |
Mean result: 1.1806715257

But there's two weird things here

1. I can't get clang to compile with `flto` unless I use their `llvm-ar`. That's annoying and my only answer RN is to check if `llvm-ar` is in their path or have the user specify it with and `LLVM_AR`. That feels kind of dumb but idk how else to handle it and worst case cmdstan just won't use flto if it can't find either.

2. We use the `unroll-loops` optimization flag, which gives like a 10% speedup on it's own. I've normally thought of that as a sort of risky optimization. But we loop so much (the entire program is essentially a giant loop lol) maybe that makes sense?

**Comment by rok-cesnovar** [comment]
> I can't get clang to compile with flto unless I use their llvm-ar

The biggest question here is probably: Does `sudo apt install clang` or equivalent on Linux install llvm-ar or is that non-standard? And does xcode on Mac come with llvm-ar?

> We use the unroll-loops optimization flag, which gives like a 10% speedup on it's own. I've normally thought of that as a sort of risky optimization. But we loop so much (the entire program is essentially a giant loop lol) maybe that makes sense?

That is nice but a bit risky to do in the final week imo.

**Comment by SteveBronder** [comment]
>> I can't get clang to compile with flto unless I use their llvm-ar

> The biggest question here is probably: Does sudo apt install clang or equivalent on Linux install llvm-ar or is that non-standard? And does xcode on Mac come with llvm-ar?

For linux yes, @wds15 does your mac have llvm-ar on it? The worst case scenario is that a user doesn't have it and then only the warning happens but everything still compiles

>> We use the unroll-loops optimization flag, which gives like a 10% speedup on it's own. I've normally thought of that as a sort of risky optimization. But we loop so much (the entire program is essentially a giant loop lol) maybe that makes sense?

> That is nice but a bit risky to do in the final week before release imo.

Yeah I totally agree that it's risky.

What we could do is put this all behind a `STAN_COMPILER_OPTIMS` make variable so users that see a slowdown can define that and opt-in to this.

**Comment by SteveBronder** [comment]
It also looks like MPI is getting some internal compiler error I need to sort out

**Comment by rok-cesnovar** [comment]
hm, on my ubuntu I have clang 10.0.0 installed and it does not have llvm-ar. 

> What we could do is put this all behind a STAN_COMPILER_OPTIMS make variable so users that see a slowdown can define that and opt-in to this.

I am cool with that. `STAN_CXX_OPTIM=true` or something sounds good to me. Would want to differentiate that its CXX optimizations not stanc.

Thanks for working on this!

**Comment by wds15** [comment]
I don‘t seem to have a llvm-ar in my path from xcode, no. I only see a few of these which come from macports.

... but I am really sure that I did use xcode‘s clang with lto and it did just work fine (with the desired speedup) for the SIR example. Should I test something, let me know.

**Comment by SteveBronder** [comment]
> hm, on my ubuntu I have clang 10.0.0 installed and it does not have llvm-ar.

> >   What we could do is put this all behind a STAN_COMPILER_OPTIMS make variable so users that see a slowdown can define that and opt-in to this.

> I am cool with that. STAN_CXX_OPTIM=true or something sounds good to me. Would want to differentiate that its CXX optimizations not stanc.

Yeah I think that makes sense

> Thanks for working on this!

np!

> I don‘t seem to have a llvm-ar in my path from xcode, no. I only see a few of these which come from macports.

> ... but I am really sure that I did use xcode‘s clang with lto and it did just work fine (with the desired speedup) for the SIR example. Should I test something, let me know.

That's odd neither of you have it, maybe I always flipped some extra thing to have it on? So turns out we only need `llvm-ar` if we compile `cvodes` with flto as well. But I just put out a version that does not do that and so doesn't need the `llvm-ar`. Kind of a bummer because it's nice to use lto across the whole program but it is what is is.

Let me run some benchmarks and then this should be good

**Comment by wds15** [comment]
Sounds like this is converging?

**Comment by rok-cesnovar** [comment]
Seems that this is close to working, except for some issue with the Jenkins mpi compiler? We could not use LTO for STAN_MPI by default if that is the case? Seems like the easiest solution.

**Comment by serban-nicusor-toptal** [comment]
> Seems that this is close to working, except for some issue with the Jenkins mpi compiler? We could not use LTO for STAN_MPI by default if that is the case? Seems like the easiest solution.

Hey @rok-cesnovar Can I help with anything here?

**Comment by rok-cesnovar** [comment]
Hey Nic, thanks but we will need to sort this out in the makefiles so no Jenkins issues here. If the compiler we use for MPI tests on Jenkins does not like these flags, we should not include them for MPI by default. It does not look like a one-off Jenkins issue or a Jenkins configurations thing.

**Comment by SteveBronder** [comment]
Just fixed it up. I put them behind a `STAN_COMPILER_OPTIMS` flag that has to be turned on in order for the optimization flags to be used

**Comment by rok-cesnovar** [comment]
Ok, but doesn't that mean we have a performance regression with the default settings which is what most users work with?

**Comment by SteveBronder** [comment]
Oh I thought we talked about putting them behind a flag so users could easily turn them on. The only regression should be in SIR or ODE models that make repeated calls to `set_zero_adjoint()`

**Comment by rok-cesnovar** [comment]
I was thinking we could put the basic `lto` flags on by default and the more involved stuff like loop unrolling behind a flag. Maybe I am complicating a bit. The regression is about 5%? 

For 5% it might be fine if we put all the LTO optimization behind a makefile flag for 2.25 and recommend that users try it out and we get feedback we incorporate for 2.26.

@wds15 what do you think?

**Comment by SteveBronder** [comment]
> For 5% it might be fine if we put all the LTO optimization behind a makefile flag for 2.25 and recommend that users try it out and we get feedback we incorporate for 2.26.

I like this. After this release we flip the flag so that they are on by default so users can report anything odd

**Comment by rok-cesnovar** [comment]
> I like this. After this release we flip the flag so that they are on by default so users can report anything odd

I meant we recommend users that require high performance try out the makefile flag in the release. I am not sure many users work with develop. 

Lets wait for Sebastian to chime in.

**Comment by wds15** [comment]
So you mean to not enable the lto speed flags by default and let users apply them manually for 2.25? If this flies well, then we turn this on for 2.26 as a default? Sounds like a plan for me. It would be great to make a note somewhere so that users will find this piece of information.

**Comment by rok-cesnovar** [comment]
> So you mean to not enable the lto speed flags by default and let users apply them manually for 2.25? If this flies well, then we turn this on for 2.26 as a default? 

Yes.

Will make sure this will be in the release notes and any “PR” posts.

**Review by rok-cesnovar — APPROVED** [review]

**Comment by SteveBronder** [comment]
@rok-cesnovar are the release notes up somewhere? I wouldn't mind sitting down today or tomorrow and writing out the narrative version (if you are not already). I think people liked that

**Comment by serban-nicusor-toptal** [comment]
Hey @SteveBronder I think you can use this Issue [here](https://github.com/stan-dev/math/issues/2128)

**Comment by rok-cesnovar** [comment]
I posted the cmdstan/stan release notes in the issue Nic linked. See https://github.com/stan-dev/math/issues/2128#issuecomment-706946996  

For Math I am waiting for the last PRs that will be merged. If you want to work on the narrative version feel free to! Havent started yet.

**Pull request merged**
