### PR TITLE
Minor typo : Missing space in error message

### PR DESCRIPTION
**Pull request by mortonjt**

### CODE REVIEW

**Comment by syclik** [comment]
@mortonjt, awesome! Thanks! I saw the same problem recently and didn't get around to fixing it.

The PR is missing the information from the Pull Request Template: https://github.com/stan-dev/cmdstan/blob/develop/.github/PULL_REQUEST_TEMPLATE.md. A lot of it isn't relevant for this PR, but please do include the copyright holder.

**Comment by bbbales2** [comment]
Also add the space to the unit test reference output `src/test/interface/example_output/mix.nom`

```
Such high values indicate incomplete mixing and biasedestimation.
```

to

```
Such high values indicate incomplete mixing and biased estimation.
```

**Comment by mortonjt** [comment]
right on, I'll open up a real PR shortly :]

**Comment by mortonjt** [comment]
Closing in favor of https://github.com/stan-dev/cmdstan/pull/996

**Pull request closed without merging**
