### PR TITLE
Issue/1029 record fixed param as override

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Summary:

Add logic to the `write_config` method to record when `fixed_param` sampler is used.

#### Intended Effect:

Make it easy to identify StanCSV output files produced by sampler algorithm `fixed_param`, both by humans as well as by `stan_csv_reader`.

#### How to Verify:

Unit tests.

#### Side Effects:

N/A

#### Documentation:

N/A

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by WardBrian** [comment]
@nhuurre before looking at this I wanted to ask if you thought we had any chance of merging something like #1054 instead and removing this fixed_param behavior, or should we continue to hack around it?

**Comment by mitzimorris** [comment]
if we could do something like #1054, then we wouldn't need to do https://github.com/stan-dev/stan/pull/3302 either.

**Comment by nhuurre** [comment]
#1054 requires stan-dev/stan#3071 . The only reason that was blocked is that Michael (betanalpha) thinks zero-dimensional spaces are one-dimensional. I have no intention of continuing to argue with him. 

I haven't seen him on github or the Stan Forums for a year or two now so I suppose we'd need someone else to review the pull request anyway. If you want me to argue about HMC and zero-dimensional topology with that _someone else_ -- yes, I can do that.

**Comment by WardBrian** [comment]
I believe the pull request was already approved, and I just took a look at it again and it seems fine, so perhaps that is the way to go

**Comment by WardBrian** [comment]
At this point we should replace this with a newer version of #1054, right?

**Pull request closed without merging**
