### PR TITLE
Add the pre-compiled header to the `build` make target.

### LINKED ISSUE #610: error: unable to open output file 'stan/src/stan/model/model_header.hpp.gch': 'Permission denied'
#### Summary:
`cmdstan` tries to create a file where it is installed but on my computer that is read only.

#### Description:

```
bin/stanc  /var/folders/h1/bkwn2ct12hvb6__dzrk5gwx80000gn/T/stanhs/s3849448837379259560.stan --o=/var/folders/h1/bkwn2ct12hvb6__dzrk5gwx80000gn/T/stanhs/s3849448837379259560.hpp
Model name=s3849448837379259560_model
Input file=/var/folders/h1/bkwn2ct12hvb6__dzrk5gwx80000gn/T/stanhs/s3849448837379259560.stan
Output file=/var/folders/h1/bkwn2ct12hvb6__dzrk5gwx80000gn/T/stanhs/s3849448837379259560.hpp
Compiling pre-compiled header
c++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem stan/src -isystem stan/lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DEIGEN_NO_DEBUG -DNO_FPRINTF_OUTPUT -pipe  -c -O3 stan/src/stan/model/model_header.hpp -o stan/src/stan/model/model_header.hpp.gch
error: unable to open output file 'stan/src/stan/model/model_header.hpp.gch': 'Permission denied'
1 error generated.
```

#### Reproducible Steps:

Install stan as another user and then try to use the installation.

#### Current Output:

See above.

#### Expected Output:

Any stan should compile.

#### Additional Information:

rStan does not exhibit this problem so maybe cmdstan can copy this?

#### Current Version:
v2.17.1

### PR DESCRIPTION
**Pull request by seantalts**
This lets us get all of the binaries out of the way at once, which is
useful for figuring out what to ship for e.g. nix packages.

Fixes #610

We need to double check that this works on all of our supported
compilers.

#### Submisison Checklist

- [x] Run tests: `./runCmdStanTests.py src/test`
- [x] Declare copyright holder and open-source license: see below

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
@seantalts, does this work on the compilers of interest? I couldn't tell if you had already checked based on the original request.

**Comment by seantalts** [comment]
Which ones are of interest? The tests pass and they execute with gcc and clang on Windows, Mac, and Linux.

**Comment by DataWookie** [comment]
Hi,

Just adding my 2 cents worth on this. I ran into the issue of not being able to build the precompiled headers too because I had installed `cmdstan` under `/opt/`, which is read only. I was trying to build a Stan model from inside Julia using https://github.com/goedman/Stan.jl.

The fix here resolved the problem for me.

Thanks, Andrew.

**Comment by seantalts** [comment]
The branch got out of date, but it was easy enough to just open a new PR. Closing this one.

**Pull request closed without merging**
